### ISSUE TITLE
Add fix for Vanilla BlockStateContainer bug

### ISSUE THREAD

**Issue by Aaron1011** [DimensionalDevelopment/VanillaFix#100]
I recently fixed a Vanilla bug in Sponge, which may have been responsible for some strange crashes people have been experiencing: https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/world/chunk/MixinBlockStateContainer.java#L75-L95

I think it would be useful to include this fix in VanillaFix. All of the Sponge code is MIT-licensed, so there shouldn't be any problems if you want to include it.

**Comment by asiekierka** [comment]
Would you mind this being included in FoamFix?

**Comment by Aaron1011** [comment]
That's fine by me. The snippet from Sponge is MIT-licensed, so you can use it wherever you want (as long as you attribute it to Sponge)

**Comment by asiekierka** [comment]
Done as of 0.10.1. The license file is included with the distribution, both source and binary, and additional attribution has been done in the changelog and the configuration file.
