### ISSUE TITLE
Suggestion to change crash report

### ISSUE THREAD

**Issue by tyler489** [DimensionalDevelopment/VanillaFix#103]
When people see //i blame {author} author of {modname} 
They immediatly report it to that github. Which is nice... what is NOT NICE is when that is wrong and the player refuses to report it elsewhere "because the crash report said it was your mod"

Could you potentially reword that line?

**Comment by Robijnvogel** [comment]
The crash report also literally says that a mod or several mods are "suspects," not passing any verdict.
If a player is too stubborn to take the advice of a programmer with an actual understanding of how a piece of software works over an educated guess that a computer presents them with, that truly is on them.

It's not like we are phrasing it as:
//There is an absolute 100% certainty that {author} made a mistake while programming {modname}. Go complain to them and don't take no for an answer.

You admit that there's a great benefit to having the crash report point out a suspected mod and author on the first line of the report, which, in my opinion, outweighs all the falsely positive reports that it may cause.

This being said, what do you propose we change it to?

**Comment by Rongmario** [comment]
There is literally no way possible to correctly determine crashes dynamically. But we can identify what is passed in the stacktraces.

**Comment by tyler489** [comment]
And im aware of that. 

Maybe something like
{Modname} was involved in the crash They May not be the cause.

Or something a  bit more simple like
Please report to {modname} they might be the cause



all in all its your choice if you want to change it or not

**Comment by Runemoro** [comment]
1. The line is an easter egg based on the vanilla "I blame Dinnerbone" comment
2. This was already changed from a 1/2 change to a 1/100 chance for the next version.

**Comment by Robijnvogel** [comment]
I don't know, Rune. I think that players are more likely to read the first line of a crash report than a specific line somewhere near the end.
It may originally have been meant as an easter-egg, but it's actually pretty functional.

**Comment by Runemoro** [comment]
The suspected mod appears on the crash screen itself. Maybe it could moved to the top section of the crash report too, along with the description and stacktrace.

In any case, if this is implemented as a feature, the probability of it being shown should be 100%, not a 1/2 chance as it is now, and it shouldn't replace the vanilla crash comment.

**Comment by Robijnvogel** [comment]
@Runemoro if that is the case, wouldn't it be wise to reopen this issue until such a change is implemented OR open a new issue for it?
