### ISSUE TITLE
Random crash VanillaFix

### ISSUE THREAD

**Issue by DatrixTHLK** [DimensionalDevelopment/VanillaFix#108]
Hi Runemoro,

I've been getting a crash when generating a new world in minecraft. I was about to punch a tree and the game Crashed.

Minecraft: 1.12.2
Forge: 14.23.4.2750
Vanilla Fix: 1.0.3-30

Crash with Vanilla Fix: https://gist.github.com/DatrixTHLK/fa99e433c922fe4217497add48ad59b5

**Comment by Runemoro** [comment]
You're using an extremely outdated version of VanillaFix. The latest version is 1.0.9-97.

**Comment by DatrixTHLK** [comment]
Yeah I just noticed that when I went to your page on curseforge. I should have looked there first. My appologies.
