### ISSUE TITLE
Crash when disabling texture fixes since I use optifine

### ISSUE THREAD

**Issue by TheRealDadbeard** [DimensionalDevelopment/VanillaFix#109]
https://hastebin.com/tapiborese.rb

**Comment by TheSnowyChickens** [comment]
I don't have Optifine installed and get a crash from Tinkers. (https://paste.dimdev.org/epaqocifuk.mccrash)

**Comment by ZombieHDGaming** [comment]
This is apparently an issue between VF and the new FoamFix version. I'd suggest rolling back either a version or 2 for the moment. I think FoamFix has only added one fix, which is something I will add this weekend alongside possibly updating to 1.13.

**Comment by TheSnowyChickens** [comment]
Then I can close my issue to this crash on the Tinkers Github? :D

**Comment by ZombieHDGaming** [comment]
Umm, sure? Go for it

**Comment by MasterEnderman** [comment]
The Crash also occurs without foamfix installed.
https://paste.dimdev.org/ajuvugeson.mccrash

**Comment by Runemoro** [comment]
The crash without FoamFix when disabling texture fixes was fixed a while ago. The crash with FoamFix is a duplicate of #110 .
