### ISSUE TITLE
NPE crash when disconnecting from Multiplayer server, loops to crash screen.

### ISSUE THREAD

**Issue by ParadoxBomb** [DimensionalDevelopment/VanillaFix#115]
When disconnecting from a multiplayer server, I get a null pointer exception that seems to be related to Clef. I am unsure if the issue is with Clef or with VanillaFix, but when clicking the "Back to Main Menu" button, the game seems to loop back to the same crash, and I am forced to close the client and re-launch the game each time.

Crash report:
https://paste.dimdev.org/uwocahihih.mccrash

Minecraft version: 1.12.2
Forge version: 14.23.4.2750 
VanillaFix version: 1.0.9-97 
Clef version: 7.0.0
iChunUtil version: 7.1.4 

See also https://github.com/iChun/Clef/issues/13

**Comment by Runemoro** [comment]
Not an issue, Clef just keeps crashing when you go to the main menu, and VanillaFix is just catching all the crashes.

**Comment by Peach774** [comment]
Uh, I also have a similar issue - is there a way to get this to be a bit less sensitive?

**Comment by Rongmario** [comment]
It's clef's fault, without VF it'll still crash, like Runemoro said it just catches all the crashes happening.
