### ISSUE TITLE
Crash with Extra Utilities 2 (latest dev build)

### ISSUE THREAD

**Issue by SanAndreasP** [DimensionalDevelopment/VanillaFix#118]
Minecraft Launcher: 2.1.1432
Forge: 1.12.2-14.23.4.2759
VanillaFix: 1.0.10-124

So I wanted to try the dev build of VanillaFix on my private modpack (~300 mods) to see if there are incompatibilities to report. I get a crash from Extra Utilities 2 whilst loading the game (during pre-init).

Here's the crash log: https://paste.dimdev.org/qixumijace.mccrash

**Comment by Runemoro** [comment]
Fixed in the latest dev build.
