### ISSUE TITLE
Latest development version crash on startup server (Sponge incompitable)

### ISSUE THREAD

**Issue by BlayzerQ** [DimensionalDevelopment/VanillaFix#120]
Crash on startup with last SpongeForge build
ClassCastException: org.dimdev.vanillafix.blockstates.NumericalBlockState cannot be cast to org.spongepowered.common.interfaces.block.IMixinBlockState
https://paste.dimdev.org/judaquqojo.rb

**Comment by ZombieHDGaming** [comment]
Please do not use the dev builds unless instructed by us due to severe issues with these builds.
