### ISSUE TITLE
New version of VanillaFix wont ping server

### ISSUE THREAD

**Issue by TacticalUniverse** [DimensionalDevelopment/VanillaFix#128]
When I updated to the new version of Vanillafix, I get the just Pinging messaging under Multiplayer and then it throws a crash and won't show the servers online unless I drop Vanillafix back a version.

https://paste.dimdev.org/rixixaceqe.mccrash

**Comment by ZombieHDGaming** [comment]
Well, this isn't a major issue, but something I will address. Just try and enter the server once you open multiplayer for now, it'll be fixed in the next release which should be soon

**Comment by TacticalUniverse** [comment]
I'll just downgrade till then

**Comment by Slayer5934** [comment]
Anyone looking for a temp fix for this can simply change B:bugFixes= to false

**Comment by xAlicatt** [comment]
Was coming to report this same issue. @TacticalUniverse don't close an issue if it's not fixed yet...
