### ISSUE TITLE
[1.12][1.0.10-99]crash with NPC's using custom sounds

### ISSUE THREAD

**Issue by mensreaMC** [DimensionalDevelopment/VanillaFix#134]
https://pastebin.com/3QgAuytp

Even if the sound file being designated is added by the Custom NPC mod I seem to get this crash when near a shooting NPC on a server. It doesn't happen in single player.

**Comment by Runemoro** [comment]
This isn't a crash. It's a warning telling you about a problem in another mod you should report to them. If you uninstall VanillaFix, the problem is still there, but will just show up in the log rather than warning you. You can disable the warning in VanillaFix's config if it's annoying.
