### ISSUE TITLE
Not a crash but annoying nonetheless

### ISSUE THREAD

**Issue by CactusDuud** [DimensionalDevelopment/VanillaFix#136]
I love VanillaFix a lot, but when putting together packs it can be annoying when the VanillaFix crash screen replaces the Forge crash screen when coremods or APIs are missing. Is there any way to disable or tweak VanillaFix to not show up if the crash is due to a missing mod?

**Comment by KingCactaur** [comment]
Alright, fair enough. Thanks for the quick reply!
