### ISSUE TITLE
Game doesn't launch at all

### ISSUE THREAD

**Issue by thebadscientist** [DimensionalDevelopment/VanillaFix#139]
The error is:
Mixin prepare failed preparing MixinEntity in mixins.vanillafix.bugs.json

Here's the full log:
https://pastebin.com/HF3vmMHJ

**Comment by ZombieHDGaming** [comment]
Well, I can tell you this, you need to update your stuff bro. First, Optifine is on E3 and your version says D3, that's a suggestion which is a good idea to follow. Second, your VanillaFix version is WAY out of of date. Your version is 1.0.8 and we are on 1.0.10 atm. Try updating that and see if your issues continues.

**Comment by thebadscientist** [comment]
> Well, I can tell you this, you need to update your stuff bro. First, Optifine is on E3 and your version says D3, that's a suggestion which is a good idea to follow. Second, your VanillaFix version is WAY out of of date. Your version is 1.0.8 and we are on 1.0.10 atm. Try updating that and see if your issues continues.

ye that worked, thanks.
