### ISSUE TITLE
net.minecraft.client.renderer.StitcherException: Unable to fit ____

### ISSUE THREAD

**Issue by SalmonSays** [DimensionalDevelopment/VanillaFix#147]
Testing mods for compatibility on the beta, and OptiFine_1.12.2_HD_U_E3 causes a mid-launch crash.

https://paste.dimdev.org/isufudubop.mccrash

**Comment by SalmonSays** [comment]
I'm not sure this should be referenced in the above ticket- there's no NullPointerException or NumericalBlockState in the ticket, as rather it's a StitcherException?

**Comment by Eddi2015** [comment]
Can confirm this with the latest Optifine preview (E4_pre1) and the latest curseforge release (1.1.1) which crashes the game with this stitcher exception: https://privatebin.net/?dee922fdf8f0b63b#tfQe7M3wHzRO192IT20NNjMtFygHn79N763iDXmQetI=

I am using a resource pack with 256x256 textures.
