### ISSUE TITLE
Beta VanillaFix 1.1-130 Crash Against Cathedral

### ISSUE THREAD

**Issue by SalmonSays** [DimensionalDevelopment/VanillaFix#149]
Testing mods for compatibility on the beta, and Cathedral-1.12.2-1.9.7h causes a mid-launch crash.

https://paste.dimdev.org/alovosatum.mccrash

**Comment by Sunconure11** [comment]
Encountering the same crash.

https://paste.dimdev.org/odajatafap.mccrash
