### ISSUE TITLE
Don't report crashes containing 'java.lang.NullPointerException' and 'NumericalBlockState' on the line below

### ISSUE THREAD

**Issue by Runemoro** [DimensionalDevelopment/VanillaFix#150]
This issue has already been reported 6 times in one hour:

- https://github.com/DimensionalDevelopment/VanillaFix/issues/149
- https://github.com/DimensionalDevelopment/VanillaFix/issues/148
- https://github.com/DimensionalDevelopment/VanillaFix/issues/146
- https://github.com/DimensionalDevelopment/VanillaFix/issues/143
- https://github.com/DimensionalDevelopment/VanillaFix/issues/142

Please stop reporting it. I'm already aware of it and working on a fix.

**Comment by KaneHart** [comment]
BTW did you guys get this error?
https://paste.dimdev.org/emexozuyuv.mccrash

Sorry I had to :P

**Comment by ScienceDrummer** [comment]
I know you guys said not to report this issue, but now I'm getting it with the newer version of VanillaFix and Draconic Evolution.

https://paste.dimdev.org/ilekihuzij.mccrash

**Comment by KaneHart** [comment]
Might want to make a new thread on that 1.32 error.

**Comment by ScienceDrummer** [comment]
Should I make a new issue for it?

**Comment by danikk14g** [comment]
i updated a few mins ago and i get a nullpointerexception with TechReborn, should i open a new issue for it?

**Comment by Runemoro** [comment]
Fixed it in the latest dev build: https://github.com/DimensionalDevelopment/VanillaFix/releases/tag/untagged-beb684940bc85ba03dcd
