### ISSUE TITLE
Startup crash with brandonscore

### ISSUE THREAD

**Issue by wormzjl** [DimensionalDevelopment/VanillaFix#156]
1.1.1-132
https://gist.github.com/wormzjl/a0d73505bb488db0fbf9880bd6fb2884

**Comment by Runemoro** [comment]
This was fixed in #133.
https://github.com/DimensionalDevelopment/VanillaFix/releases/latest

**Comment by KaneHart** [comment]
was this already sent to curse? I guess their a bit slow still these days.
