### ISSUE TITLE
Crash in Game

### ISSUE THREAD

**Issue by ScienceDrummer** [DimensionalDevelopment/VanillaFix#157]
I installed the latest project version of the mod and after moving around for a bit in a new world, I get these 2 crashes.

https://paste.dimdev.org/cazaqixiku.mccrash

https://paste.dimdev.org/irujorowut.mccrash

**Comment by Runemoro** [comment]
Disable Optifine's "Smart Animations". VanillaFix includes the same fix as Optifine.
