### ISSUE TITLE
Please stop using @Overwrite

### ISSUE THREAD

**Issue by darkhax** [DimensionalDevelopment/VanillaFix#16]
From what I understand, when you use Overwrite, your mixin will not be compatible with any other mixin that modifies that method. Using Inject instead should lead to making your code significantly cleaner, and also fix those compat issues. It also means that any new changes Forge makes to those methods will be unintentionally reverted by your mod.

**Comment by Runemoro** [comment]
We're using overwrite in 5 places:
 - MixinEnchantmentHelper.get___ (we are replacing a static field with a local variable, not possible with mixins)
 - MixinNetHandlerPlayServer.processPlayer (we're rewriting that method from scratch, completely different than vanilla)
 - MixinNetHandlerPlayServer.processConfirmTeleport (same thing, as a consequence of the above)
 - MixinUtil.runTask (we're modifying the catch blocks, not possible with inject)
 - Minecraft.run (we're modifying catch blocks, not possible with inject)

All of the other methods are mixins are either Injects or Redirects
