### ISSUE TITLE
Startup Crash with v132

### ISSUE THREAD

**Issue by AngelusQQ** [DimensionalDevelopment/VanillaFix#160]
I removed all mods, and JVM arguments, and Resource Packs.

Forge Version: 2768

After pressing Start Game, immediately crashes
VanillaFix-1.0.10-99 was working

Latest Log: https://pastebin.com/zJtW38AG

**Comment by Runemoro** [comment]
Your log says you're using `VanillaFix-1.0.10-124.jar`. Is this the wrong log, or are you actually using that version?

**Comment by AngelusQQ** [comment]
Apologies, I kept trying other versions, stopped at 1.0.10-124

**Comment by border999** [comment]
this issue also still exists in every version after

**Comment by border999** [comment]
as well as an issue where "Video settings"  is inaccessible because it crashes when you try.

**Comment by ZombieHDGaming** [comment]
Because this version is not meant for public use. I'm gonna close this issue as this feature/build set most likely won't be updated any time soon.
