### ISSUE TITLE
Crash with visuals

### ISSUE THREAD

**Issue by Eddi2015** [DimensionalDevelopment/VanillaFix#163]
Forge version: 2805

Installed mods:

- VanillaFix version: 1.1.1-134 (latest untagged)
- Visuals: 2r (GitLab: https://gitlab.com/DragonForge/visuals/tree/1.12.2)
- HammerCore: 2.0.4.1, a library Visuals depends on (GitLab: https://gitlab.com/DragonForge/HammerCore)

Finally the crash report: https://paste.imirhil.fr/?e3a1e1c0d248cb93#FilfNpXuHvaNcUAyZvB3IsLbtu4Fp9xKGALLSqYLDTw=

**Comment by Dinolek** [comment]
https://gitlab.com/DragonForge/visuals/merge_requests/1/diffs

**Comment by Runemoro** [comment]
Closing this since the crash report is gone,, please don't use temporary pastes.
