### ISSUE TITLE
minecraft crash log: DuplicateModsFoundException

### ISSUE THREAD

**Issue by Jacky10X** [DimensionalDevelopment/VanillaFix#17]
Minecraft version: 1.12.2
mod version: VanillaFix-1.0.3-22.jar
crash log:
https://pastebin.com/iuzVHVF9
but i have only one mod installed (no 2 VanillaFix-1.0.3-22.jar in the mods only one)

**Comment by Runemoro** [comment]
Duplicate of #1. Either use the latest CurseForge release, or recommended forge 2655. The fix for bug #1 breaks the mod from loading in dev, so we're only making it work with forge 2655+ in releases.
