### ISSUE TITLE
Using Optifine issue

### ISSUE THREAD

**Issue by GuerreroCraft61** [DimensionalDevelopment/VanillaFix#172]
Without Optifine: [https://i.gyazo.com/fa246ba4b78099179d7bfa24bf78eb01.mp4](https://i.gyazo.com/fa246ba4b78099179d7bfa24bf78eb01.mp4)
Using Optifine: [https://gyazo.com/fa246ba4b78099179d7bfa24bf78eb01](https://i.gyazo.com/cb3738f8d1ee4fa3a67de7d8375cd031.mp4)

If I disable texture optimization in the config, the animation work

**Comment by Dimentive** [comment]
Is “Textures Animated” in the video settings enabled when you have OptiFine installed?

**Comment by Dimentive** [comment]
Are “Textures Animated” and “Terrain Animated” in Options → Video settings → Animations enabled when you have OptiFine installed?

**Comment by GuerreroCraft61** [comment]
yes, is enable

**Comment by ZombieHDGaming** [comment]
I'm gonna say that's probably either a mod conflict, or you're using an older version VanillaFix cause I use this in my own private pack and there is no issues.

**Comment by lostallmymoney** [comment]
I'd like to reopen the issue for latest VanillaFix + latest optifine on 1.12.2

**Comment by MrRedstoneA1** [comment]
> I'd like to reopen the issue for latest VanillaFix + latest optifine on 1.12.2

I opened a new issue on this regarding animated emissive textures being frozen with version numbers.
