### ISSUE TITLE
VanillaFix + Sponge + JustEnoughID's = Game not Launching

### ISSUE THREAD

**Issue by LokeYourC3PH** [DimensionalDevelopment/VanillaFix#173]
So as soon as I try to add VanillaFix to my current modpack installation, the game refuses to launch at all, without it launches just fine. Here is the startup log from the Technic Launcher/Game. It doesn't generate a crash-report at all as it never comes far enough to do so.

Log: https://pastebin.com/4vpRUU1e

**Comment by GrandAlbert** [comment]
I'm having the same problem too but I don't have sponge or jei installed
