### ISSUE TITLE
Bed Bugs are not fixed

### ISSUE THREAD

**Issue by ExDomino** [DimensionalDevelopment/VanillaFix#174]
Hello,

With your mod installed, Bed Bugs are not fixed. I have been stuck in my bed and only way to exit was an Alt + F4. Your mod did nothing to fix that bug.

Version : 1.0.10-99 for 1.12.2.

**Comment by ZombieHDGaming** [comment]
Go yell at Forge. With 1.0.10, we removed that feature as Forge implemented the exact same fix, so there was no point of a double fix included.

**Comment by ExDomino** [comment]
But it seems that Forge doesn't fix that bug either. I had to install the mod Bed Bugs.

**Comment by Runemoro** [comment]
> But it seems that Forge doesn't fix that bug either. I had to install the mod Bed Bugs.

Update to the latest version of forge

**Comment by ExDomino** [comment]
I'm already to the latest version of Forge. 2821
