### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by Dimentive** [DimensionalDevelopment/VanillaFix#175]
I got this error in the server console: https://pastebin.com/raw/jrevCety

I’m playing on a local server with one other person, but only he was on the server when this error happened in the console. It had no effect on the game itself and didn’t cause a crash, but I’m reporting it nonetheless.

**Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (with some mods added, including VanillaFix)
**Modpack version:** 1.62 (latest as of today)
**VanillaFix version:** 1.0.10-99 (latest as of today)
**Forge version:** 14.23.5.2781

**Comment by Runemoro** [comment]
This is caused by bibliocraft, not vanillafix.

**Comment by Dimentive** [comment]
Oh, my apologies. I just read “[VanillaFix]” at the top and assumed that it was this mod.
