### ISSUE TITLE
[1.12.2] Botania + VanillaFix incompatibility issue

### ISSUE THREAD

**Issue by wiloxe** [DimensionalDevelopment/VanillaFix#18]
https://github.com/Vazkii/Botania/issues/2630

**Comment by ZombieHDGaming** [comment]
You're on 1.0.1-6. We've released a new version on CurseForge, please test on that version and let us know if the problem still happens with the new log file.

**Comment by Runemoro** [comment]
This is not a bug (in 1.0.1 or 1.0.2) but rather a **feature** to warn you about an issue that may cause more serious problems later. By default, Minecraft does not crash on scheduled exceptions, but rather only logs an error message resulting in bugs that are very difficult to solve.

In VanillaFix 1.0.2 (the latest version on CruseForge), the crash is replaced with a warning screen only.

**Comment by Hillage** [comment]
@Runemoro Please see the following crashlog. There is no crash/warning with ONLY Botania and Baubles, but as soon as you add VanillaFix it crashes/throws a warning screen (perhaps as intended, but without VanillaFix the game is completely playable)

https://paste.dimdev.org/bazujeseze.txt

If you have any insight on if VanillaFix causes this, or just unfortunately picks up an error that doesn't affect the player's experience, it would be appreciated. We'd like to figure it out either way.

**Comment by ZombieHDGaming** [comment]
@Hillage We've already stated this an issue with Botania. That is just a warning that this is happening with Botania. Please report the issue to them about this for support as this is their issue.

**Comment by Runemoro** [comment]
@Hillage The warning screen is intended. It warns you about a Botania problem that is likely to affect the player's experience in some way, and creates a report rather than silently ignoring the issue to help the mod developers to fix it. You should send that report to Botania.

Otherwise, if you find the warning screen too annoying, you can change it to log a message only.
