### ISSUE TITLE
Failed to identify error report

### ISSUE THREAD

**Issue by DWX12** [DimensionalDevelopment/VanillaFix#181]
Crash upon trying to load a brand new world. Report said to post it here:

https://paste.dimdev.org/ihetixesod.mccrash

Thanks for all your work guys and let me know if you need more info.

**Comment by Runemoro** [comment]
The crash is caused by Random Tweaks. The mod identification not working is a duplicate of #113.

**Comment by DWX12** [comment]
Alright thanks, atleast I have an idea of what's going on and where to look.
