### ISSUE TITLE
VanillaFix prevents my game from starting

### ISSUE THREAD

**Issue by yorik100** [DimensionalDevelopment/VanillaFix#183]
1.12.2 Forge, Windows 7, latest version of java, it simply start (only seeable in task manager), RAM going up as it normally is, as the game starts, suddently close, the Minecraft window never appear

**Comment by ZombieHDGaming** [comment]
Possibly the log from the launcher, or the debug.log? We can't do anything without knowing what the issue is. This could be caused from almost anything

**Comment by yorik100** [comment]
https://pastebin.com/n7m5K0Y4

**Comment by Gunner76th** [comment]
@yorik100 I know this is over a year old and you probably do not even have the logs anymore. However, in the future when submitting crash reports and log files, upload the ENTIRE log file not a snippet. The latest.log log file contains massive amounts of information in it, and oftentimes what you think is causing the problem isnt. By providing only a snippet, you might think you are helping us by filtering out all the extra stuff, but it's that extra stuff that paints the whole picture and tells us what is fully happening.

**Comment by yorik100** [comment]
> 
> 
> @yorik100 I know this is over a year old and you probably do not even have the logs anymore. However, in the future when submitting crash reports and log files, upload the ENTIRE log file not a snippet. The latest.log log file contains massive amounts of information in it, and oftentimes what you think is causing the problem isnt. By providing only a snippet, you might think you are helping us by filtering out all the extra stuff, but it's that extra stuff that paints the whole picture and tells us what is fully happening.

It was incompatibility with other mods

**Comment by Gunner76th** [comment]
> > @yorik100 I know this is over a year old and you probably do not even have the logs anymore. However, in the future when submitting crash reports and log files, upload the ENTIRE log file not a snippet. The latest.log log file contains massive amounts of information in it, and oftentimes what you think is causing the problem isnt. By providing only a snippet, you might think you are helping us by filtering out all the extra stuff, but it's that extra stuff that paints the whole picture and tells us what is fully happening.
> 
> It was incompatibility with other mods

Do you happen to remember what other mods, and how you determined this?

**Comment by yorik100** [comment]
> 
> 
> > > @yorik100 I know this is over a year old and you probably do not even have the logs anymore. However, in the future when submitting crash reports and log files, upload the ENTIRE log file not a snippet. The latest.log log file contains massive amounts of information in it, and oftentimes what you think is causing the problem isnt. By providing only a snippet, you might think you are helping us by filtering out all the extra stuff, but it's that extra stuff that paints the whole picture and tells us what is fully happening.
> > 
> > 
> > It was incompatibility with other mods
> 
> Do you happen to remember what other mods, and how you determined this?

Not at all

**Comment by Runemoro** [comment]
> FumeObfuscator

Not caused by VanillaFix. It seems like some mod is messing with Mixin.
