### ISSUE TITLE
Incompatibility with Optifine

### ISSUE THREAD

**Issue by kenijey** [DimensionalDevelopment/VanillaFix#19]
it crashes when i put VanillaFix in my modpack...
[crash-2018-05-16_12.18.58-client.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/2008387/crash-2018-05-16_12.18.58-client.txt)
[crash-2018-05-16_12.22.03-client.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/2008388/crash-2018-05-16_12.22.03-client.txt)
second one that i deleted foamfix if it causes but no...

**Comment by kenijey** [comment]
oh.. got the problem, it crashes with OptiFine... i'm using OptiFine 1.12.2 HD U D3 and it crashes with it. no crash if i remove optifine from my modpack... need help from @sp614x?

**Comment by Runemoro** [comment]
I'll try fixing this for next version

**Comment by kenijey** [comment]
thanks so much

**Comment by Sunconure11** [comment]
Is this crash related, by any chance?

https://pastebin.com/AryzqRvm

**Comment by Runemoro** [comment]
Fixed in the latest dev build.
