### ISSUE TITLE
Option to disable the toasts

### ISSUE THREAD

**Issue by LiskoSlayer63** [DimensionalDevelopment/VanillaFix#191]
I would like the disable option for the toasts which are telling me that theres probably something wrong with mod X. I want to see them when I'm looking for errors, but not when I'm just playing normally.

**Comment by Runemoro** [comment]
Open the VanillaFix settings menu and set "Scheduled Task Error Action" to "Ignore".

**Comment by LiskoSlayer63** [comment]
@Runemoro There's no such option. The options are: `NOTIFICATION`, `WARNING_SCREEN`, `CRASH` and `LOG`.

**Comment by Runemoro** [comment]
Sorry, I meant `LOG`.

**Comment by LiskoSlayer63** [comment]
@LiskoSlayer63 Oh, thank you for the quick answers!
