### ISSUE TITLE
Immersive Engineering Conveyor Belts not animating

### ISSUE THREAD

**Issue by LiskoSlayer63** [DimensionalDevelopment/VanillaFix#192]
The title says it all, conveyor belts from IE are not animating at all, makes it hard to determine which direction they are moving. Also flowing water isn't animating (Optifine anti-aliasing is off).

**ImmersiveEngineering:** 0.12-89
**VanillaFix:** 1.0.10-99

**EDIT:** _Wasn't bug at all, user fault._

**Comment by Runemoro** [comment]
Do the issues happen without Optfine? If not, what's your Optifine version? An Optifine update may have broken the animated textures.

**Comment by LiskoSlayer63** [comment]
@Runemoro It does happen even if Optifine is not installed if I remember right, I'm mainly using it though. Optifine version is **1.12.2 HD U E3**.

**Comment by LiskoSlayer63** [comment]
Noticed today that the blinking leds from [Redstone Gauges and Switches](https://www.curseforge.com/minecraft/mc-mods/redstone-gauges-and-switches) are not blinking, they just turns on statically instead.

**Comment by LiskoSlayer63** [comment]
This wasn't a bug, wrong alert. I just had disabled texture animations in FoamFix configuration. Sorry for bothering, closing this now.
