### ISSUE TITLE
Items and blocks of most mods have no textures with this mod

### ISSUE THREAD

**Issue by chinesexs** [DimensionalDevelopment/VanillaFix#193]
I dont know what to say,but when I updated this mod from 1.0.10-99 to 1.1.1-138,lots of textures have missing
For example,TConstruct's tools all turned to fully white.
For another example,mekanism's machine all turned to fully black
For another another example,when i try to check recipes of Extreme Crafting Table of Avaritia in JEI or even just open it,the game just crashed cause gui missing
And I have enough reasons to believe all these deadly issues are caused by the version 1.1.1-138 of this mod.
But in other hand,I put too many mods so this may be caused by two or more mods.
Perhaps it has to do with MakeZoomZoom mod and Dynamic Resource feature of this mod?
Or the problem is just cursed by this mod alone.

**Comment by Runemoro** [comment]
Duplicate of #153. The latest curseforge is 99 for a reason, use that one.
