### ISSUE TITLE
Conflict with many mods now

### ISSUE THREAD

**Issue by madokaorimura** [DimensionalDevelopment/VanillaFix#194]
Conflict SpongeForgr, Tinker Construct, TexFix, etc.
Forge: 14.23.5.2838

**Comment by madokaorimura** [comment]
Tinker Construct: https://gist.github.com/madokaorimura/aad228a748f04df74595adc16555d70a
SpongeForge: https://gist.github.com/madokaorimura/f5bbeefeb1ec80543a6a6dd510f86cfc
TexFix: https://gist.github.com/madokaorimura/4b3afe42a7532e1b39ff9fac73faa3cb

**Comment by ZombieHDGaming** [comment]
That doesn't tell us anything. We need more info such as, a log, modlist, mod version, etc.

**Comment by madokaorimura** [comment]
Here we go

**Comment by madokaorimura** [comment]
and also the problem with VanillaFix-1.0.10-99
Console log only: https://gist.githubusercontent.com/madokaorimura/21451ed6ef8924068afd6f4ec5d90005/raw/f07efdc7997cda4581689cce1bd6da7de3ff762f/2019-06-25-4.log

**Comment by madokaorimura** [comment]
Mods/Plugins on server: https://gist.github.com/madokaorimura/c6bc493159864ea604cc16aaef07d4a0
Mods on client : SkyFactory4 4.0.8 modpack with additional: BetterFps, VanillaFix, Phosphor, TexFix, FPS Reducer, FoamFix, and OptiFine
