### ISSUE TITLE
Incompatibility with Wizardry

### ISSUE THREAD

**Issue by CvoidWyvern** [DimensionalDevelopment/VanillaFix#20]
This error does not exist on 1.0.2.  This log is from a fresh instance with just these two mods and required libraries installed.

https://paste.ee/p/eOQuv

Corresponding issue on wizardry github:
TeamWizardry/Wizardry#137

**Comment by Runemoro** [comment]
Thanks for the report, I'll fix this for next release. The animation optimization has to be adjusted to be compatible with a few mods apparently.

**Comment by Runemoro** [comment]
Fixed in the latest dev build.
