### ISSUE TITLE
Reoccurring popup message depicting a crash that doesn’t actually crash.

### ISSUE THREAD

**Issue by SirAron111** [DimensionalDevelopment/VanillaFix#209]
https://github.com/Cryptic-Mushroom/The-Midnight/issues/296
There is a strange issue with the Midnight mod that keeps popping up these messages. But even if vanillafix isn’t installed it doesn’t crash. It seems like maybe it does detect a problem but the problem doesn’t lead to a crash or to something else is there an option to disable certain popup like these if not in creative mode? Or to ignore this specific problem! Maybe vanillafix just can’t handle a certain special trait of the midnight mod that bridges the portals to exist in both dimensions and treats it as a problem?

**Comment by ZombieHDGaming** [comment]
This actually isn't a VanillaFix issue, VanillaFix is actually warning of an OutOfBounds error. I gurantee you that if you look in the log while playing, that issue should most certainly still arise, it'll just be silent. If the devs of The Midnight look, they should find an issue in their logic based on what seems to happen. I'll pop over to their repository to see where it's happening soon.

**Comment by Trnrr** [comment]
I just wanted to say I get this too at random sometimes. I don't use that pack or mod or whatever is linked above. I asked at forge discord and someone said my crash is a vanilla networking problem. Crash:
https://gist.githubusercontent.com/Trnrr/0aed4a2731b81b955215fea7762bf634/raw/01f7df83002ecf915bf4f498884efcaaa7e2cd32/crash
Debug:
https://gist.githubusercontent.com/Trnrr/67ce1ea27e7a5177a2340d7b1d107048/raw/676bc1a48e30f06c55b004034f6e53c08189a5c7/debug.log
It just spams over and over sometimes and makes the logs like 100k lines long lol. Not sure if its vanillafix's problem but just wanted to post in case it helps in any way.

**Comment by SirAron111** [comment]
Would it be possible for vanillafix to ad an option to not show the same error over and over again? I mean getting notified once or twice about and error is enough? But if something like this which doesn’t cause a crash gets spammed on the screen all the time its getting annoying for players. Or is there an option to only have the message pop up in creative mode?..if I work on stuff and fix stuff for my modpack its handy having this error message pop up but when I release the pack and the players than still get the endless popups looping for common mods like chancecubes or midnight or thermal just because of something that doesn’t even do much it’s kind of problematic.

**Comment by SirAron111** [comment]
its a realy anoing problem https://www.twitch.tv/videos/486064696?t=1h22m18s is it possible to fix it if i change the settings to not do notifications and make it to log or so or would that spam the log? is there no setting to disable the notification feature compleatly.
