### ISSUE TITLE
java.lang.IllegalAccessError: org/dimdev/vanillafix/mixins/MixinUtil$1

### ISSUE THREAD

**Issue by Bneboy** [DimensionalDevelopment/VanillaFix#21]
Hey, I get this crash when I tried to get into my world.
The crash message said the possible mod that caused the crash was unknown.
Juding by the crash report, it seems like it's VanillaFix itself? Though I don't know for sure.

Crash report:
https://pastebin.com/JTALgGHP

**Comment by DatrixTHLK** [comment]
I have a similar issue located on ArtixAllMighty's Github page with Vanilla Fix [Issue 34](https://github.com/ArtixAllMighty/Telepads2016/issues/34)

**Comment by Runemoro** [comment]
Does it also happen without Telepads installed?

**Comment by Zer0Lyfe** [comment]
also happened to me:
https://paste.dimdev.org/dosugokomo.txt

**Comment by DatrixTHLK** [comment]
It does not happen unless that mod is installed.

**Comment by Runemoro** [comment]
Fixed in the latest dev build.

**Comment by Runemoro** [comment]
Note: This seems to be a bug with Mixin, similar to https://github.com/SpongePowered/Mixin/issues/31.
