### ISSUE TITLE
VanillaFix GUI Loop: 1282: Invalid Operation spamming the log.

### ISSUE THREAD

**Issue by matyklugDebbuged** [DimensionalDevelopment/VanillaFix#211]

**Comment by Runemoro** [comment]
Can't do anything until you upload a log. Is there a way you can reproduce this? Try F3 + C to force a crash. Does the log spam always happen, or just after a specific crash?

**Comment by matyklugDebbuged** [comment]
[2019-10-10-2.log.gz](https://github.com/DimensionalDevelopment/VanillaFix/files/3711119/2019-10-10-2.log.gz)
