### ISSUE TITLE
option to disable and enable notifications

### ISSUE THREAD

**Issue by NordicGamerFE** [DimensionalDevelopment/VanillaFix#213]
i wish there was a option to disable and enable notifications
![image](https://user-images.githubusercontent.com/18188155/66872927-74d1e380-efa7-11e9-9cf1-39aa372da951.png)

**Comment by ZombieHDGaming** [comment]
There is. It's been there since the notifications were introduced.

**Comment by NordicGamerFE** [comment]
where do i find this option?

**Comment by ZombieHDGaming** [comment]
It's under the crashes config section.
