### ISSUE TITLE
Crash with VanillaFix-1.0.3-30 + OptiFine_1.12.2_HD_U_D2

### ISSUE THREAD

**Issue by SextupleTap** [DimensionalDevelopment/VanillaFix#22]
When loading up the game when forge is constructing mods, past the 2/7 or 3/7 point the game just crashes when both VanillaFix and Optifine are installed together, this crash just makes the game close while it is constructing the mods without leaving a crash log behind. Removing Optifine from the mods list makes the game no longer crash, and if you remove VanillaFix and keep Optifine the game won't crash. So something is going on between the two mods.

The forge version is also:
14.23.3.2655 - 1.12.2

Edit: The new latest version of Optifine also causes this problem - Version OptiFine_1.12.2_HD_U_D3

**Comment by Runemoro** [comment]
Yes, as mentionned on the CurseForge page, 1.0.3 is not compatible with Optifine.
