### ISSUE TITLE
1.14 ver?

### ISSUE THREAD

**Issue by thegamerx1** [DimensionalDevelopment/VanillaFix#221]
Will this mod get any 1.14 version?

**Comment by S-B99** [comment]
Duplicate of #216

**Comment by notspaceuwu** [comment]
My issue was opened to better support SpongeForge, not for a mod to be updated to a newer version of Minecraft.

**Comment by BoogieMonster1O1** [comment]
This is getting a 1.16 version. Check the 1.16 branch
