### ISSUE TITLE
Random damage ticks while walking/sprinting/sprint jumping

### ISSUE THREAD

**Issue by HueboWasTaken** [DimensionalDevelopment/VanillaFix#227]
issue #44 still not resolved, single damage ticks are still randomly given.

Version: 1.0.10-99

**Comment by ZombieHDGaming** [comment]
This is not possible as we removed all those changes back before 1.0.8 I believe. There is no remnant of those and have not experienced such issues in my own testing, considering I love playing with VanillaFix in my instance. This is most likely contributed from another mod if I had to guess, as no one has complained again of such issues after we released versions above 1.0.7 and I haven't experienced it either.
