### ISSUE TITLE
incompability with arcane archives

### ISSUE THREAD

**Issue by nightloli** [DimensionalDevelopment/VanillaFix#240]
Crash on minecraft startup
mods:
arcane archives 0.2.0.16
mysticallib 1.7.0
vanillafix 1.0.10-150
latest.log:
https://pastebin.com/QuhMM7nu

**Comment by ZombieHDGaming** [comment]
This is because Arcane Archives uses belie Mixins 0.8, I would make an issue with them and tell them to update.

**Comment by noobanidus** [comment]
Will post an update shortly.
