### ISSUE TITLE
Crash on boot, probably the mixins thing, I dunno.

### ISSUE THREAD

**Issue by PurpleHel** [DimensionalDevelopment/VanillaFix#241]
Just gonna switch back to the previous version of vanilla fix, but figured I'd throw logs your way first.
https://pastebin.com/EF3DGtNm debug.txt
https://pastebin.com/cQZPK4JA latest.txt
https://pastebin.com/TMkVq2W6 mods list (yes, there's lots.)
MC 1.12.2
MultiMC 0.6.10-develop-1428
VanillaFix 1.0.10-150

**Comment by ZombieHDGaming** [comment]
Yes, one or more of your mods are using an outdated Mixins version. I would suggest you put the pressure on them to update as this is not an issue with us, and more them.

**Comment by PurpleHel** [comment]
Eh, I'll just stick with the previous version of vanillafix for now. No attention span for trying to figure out which other mod is the problem.

**Comment by ProsperCraft** [comment]
Just a note here I know you don't have it, but SGcraft is one of the mods that needs updated Mixins.
https://github.com/AlmuraDev/SGCraft/issues/145

**Comment by ZombieHDGaming** [comment]
SGCraft is already updated to Mixins 0.8, they just haven't released an update with it.
