### ISSUE TITLE
Minecraft doesn't start

### ISSUE THREAD

**Issue by RodrigoTaipe93** [DimensionalDevelopment/VanillaFix#245]
With the latest version the game doesn't start.

Here is the log, just in case this is needed:

- https://paste.ee/p/GbKZA

**Comment by Zack7292** [comment]
i've also got a issue of the same type logs: https://pastebin.com/y0gS31qi

**Comment by Keetarin** [comment]
Same here: https://pastebin.com/PP0dVepF

**Comment by benblack456** [comment]
same issue. v1.0.10-150 causes an immediate crash on launch in any and all instances of Minecraft i tested it on, all of which were on Forge v14.23.5.2847, and included a standalone test.

**Comment by ZombieHDGaming** [comment]
I'll address all of these right now:
@RodrigoTaipe93 and @Keetarin, you both need to yell at Bewitchment to update their Mixins as they should be updating it to prevent issues

@Zack7292 You need to update ArcaneArchives as that mod has already updated to fix this

@benblack456 I can't help you without a log, but I will call you out on the standalone test
![VanillaFix](https://user-images.githubusercontent.com/10361287/78203885-24234980-7466-11ea-93fc-c40f311e6fe3.PNG)
As I always test that it can launch before release and love to use my own mod in testing first

**Comment by benblack456** [comment]
> I'll address all of these right now:
> @RodrigoTaipe93 and @Keetarin, you both need to yell at Bewitchment to update their Mixins as they should be updating it to prevent issues
> 
> @Zack7292 You need to update ArcaneArchives as that mod has already updated to fix this
> 
> @benblack456 I can't help you without a log, but I will call you out on the standalone test
> ![VanillaFix](https://user-images.githubusercontent.com/10361287/78203885-24234980-7466-11ea-93fc-c40f311e6fe3.PNG)
> As I always test that it can launch before release and love to use my own mod in testing first

my apologies, you're entirely correct. standalone launch works fine, my bad 😬

**Comment by RodrigoTaipe93** [comment]
Got it! I just notified the author of Bewitchment! Hopefully it will be fixed soon! :)
Thank you! :)
