### ISSUE TITLE
Crash on launch with malisisdoors

### ISSUE THREAD

**Issue by yourmum21** [DimensionalDevelopment/VanillaFix#248]
I encountered the same error in version 1.0.10-150 of VanillaFix (and malisiscore1.12.2-6.5.1, malisisdoors-1.12.2-7.3.0) **HOWEVER** did i test it with version VanillaFix-1.0.10-99 which is the 2. newest version at this moment, which **launched the game properly**.

Hope this helps, sorry to bother if you dont care / it's to hard to make this compatible.

Edit: Just read in your version 150 changelog that other mods possibly haven't updated their Mixins version, could be that i guess?

Crash log: https://pastebin.com/tDYGBPvj

_Originally posted by @yourmum21 in https://github.com/DimensionalDevelopment/VanillaFix/issues/144#issuecomment-609058056_

**Comment by TerdyTheTerd** [comment]
My issue now is when using all the latest versions it won't load (nothing loads, jvm gets frozen before the minecraft window opens) and if everything BUT Vanillafix is most recent then it loads just to crash about a missing mixin class...

**Comment by BoogieMonster1O1** [comment]
Read the pinned issues (#296 and #265)
The problem lies with malisisdoors using an older version of mixin than the one that vanillafix uses
