### ISSUE TITLE
Another Old Mixin Version Crash

### ISSUE THREAD

**Issue by CitrusHappy** [DimensionalDevelopment/VanillaFix#249]
using latest vanillafix version 1.0.10-150

[crash1](https://paste.dimdev.org/qosotajizi.mccrash)

**Comment by ZombieHDGaming** [comment]
DynamicSurroudings is the culprit.

**Comment by ScienceDrummer** [comment]
DynamicSurroundings has fixed it. Coming next update. https://github.com/OreCruncher/DynamicSurroundings/issues/556
