### ISSUE TITLE
Weird Codeline Crash (affects some in-game assets)

### ISSUE THREAD

**Issue by ChessieSeaboard** [DimensionalDevelopment/VanillaFix#250]
originally downloaded some resourcepacks for a mod called Immersive Railroading, along with a mod known as buildcraft. This started happening with start crash screen and mods tab, and a few other things.

Start crash error: https://gyazo.com/76cf66171f55765d738fa8714c24095c

menu error (fml.menu.mods shouldn't be there): https://gyazo.com/3f187de413aed7f28f2ca439b08d18d7

**Comment by ZombieHDGaming** [comment]
I'd like to say this is because of us, the unformattes lang isuse hasn't been an issue since the first versions of the mod. This has to be something for either Immersive Railroading or Buildcraft as this doesn't happen normally.
