### ISSUE TITLE
Minecraft with VanillaFix 1.0.10-150 (1.12.2) doesn't start

### ISSUE THREAD

**Issue by TImmigamer06** [DimensionalDevelopment/VanillaFix#254]
Minecraft doesnt start when i have installed the Mod
( I use Forge 14.23.5.2820 )

**[latest.log](https://github.com/DimensionalDevelopment/VanillaFix/files/4494311/latest.log)**

**Comment by ZombieHDGaming** [comment]
If DynamicSurroundings isn't updated yet, update it to the latest, and get rid of MovingWorld, it is using EXTREMELY outdated Mixins and, from what I remember, isn't being updated anymore

**Comment by TImmigamer06** [comment]
thank you it works now :D
