### ISSUE TITLE
VanillaFix v150 +MalisisCore - Mixins compatability bug

### ISSUE THREAD

**Issue by Terminal-Access** [DimensionalDevelopment/VanillaFix#255]
**Version:** 6.5.1
**MC Version:** 1.12.2
**Forge Version:** 14.23.5.2854

**VanilaFix Version: ** 1.0.10-150

**Conflicting Mod:**
**Name:** MalisisCore
**Version:** 6.5.1 (possibly all previous builds for MC 1.12.2)

**Note:**
Have reported the incompatibility over at the [MalisisCore github issues page](https://github.com/Ordinastie/MalisisCore/issues/172)  as well, as they are also incompatible with the newer builds of spongeforge that also use mixins v 0.8.

**Dirty Workaround**
I have included SpongeForge in the example in case there are those out there running SF aswell.

Rename Spongeforge to _aaa.Spongeforge...jar
Rename Vanilla Fix to _aab.VanillaFix...jar

This forces SpongeForge and then VanillaFix to load before MalisisCore thus forcing usage of the newer mixins 0.8 version

Thanks for all your hard work, it's really apreciated!

Many kind regards
Lee.

**Comment by Terminal-Access** [comment]
Going to shortly publish a new repo for thermos as i've made some advancements however

Just to further address your issue the line below states you your working outside of a git repository.
`fatal: not a git repository (or any of the parent directories): .git
`

For the build to work you have to use git and clone using the resursive option
then your able to the ./gradlew clean setupCauldron installbundle
that will compile and create the server (currently still bugged on this repo however)

wait for the new repo to appear and ill have instructions waiting.

**Comment by Terminal-Access** [comment]
Accidently replied to the wrong issue and closed, so reopening as this issue is still current.

**Comment by ZombieHDGaming** [comment]
This is not an incompatibility, it already supports it in the fork of it, it just needs to be built.
