### ISSUE TITLE
VanillaFix 1.0.10-150 + BetterFPS Crash

### ISSUE THREAD

**Issue by GuerreroCraft61** [DimensionalDevelopment/VanillaFix#258]
I change VanillaFix to VanillaFix-1.0.10-99 and it work

Log: https://gist.github.com/GuerreroCraft61/17c3ac4cbb8729f511339a74bdadbe83

**Comment by sergeycherepanov** [comment]
The issue still present in latest releases.

**Comment by dominic-03** [comment]
It's likely a Mixin bug, as 1.0.10-150 updated Mixin to 0.8.

**Comment by BoogieMonster1O1** [comment]
Read the pinned issues (#265 and #296)
