### ISSUE TITLE
Minecraft with VanillaFix 1.0.10-150 (1.12.2) still doesn't start 

### ISSUE THREAD

**Issue by CactusDuud** [DimensionalDevelopment/VanillaFix#259]
I've removed Dynamic Surroundings to test only VanillaFix, and there's still an error.
Disabling VanillaFix allows minecraft to start.

https://pastebin.com/eUbErRmj

**Comment by ZombieHDGaming** [comment]
1. DynamicSurroundings is still installed.
2. This is not an issue with VanillaFix, a mod is causing transform issues and Mixins can't do anything as the class has already been modified before we could do anything.
