### ISSUE TITLE
Problem with MalisisDoors and Buildcraft

### ISSUE THREAD

**Issue by Swandar** [DimensionalDevelopment/VanillaFix#260]
If I load VanillaFix along with Malisis, the game just doesn't even load. I click play, wait 5 seconds, and it says "sorry game has crashed"

Disabling it I get all the way through, only to be told Buildcraft crashes it, all modules of it too.

I've tried loading it in a new fresh instance with only Malisis and Buildcraft, Malisis still crashes it before it can load. But Buildcraft manages to make it through. I'll post the .log and crash report here. I'll also post a .zip containing the manifest.json for the mods I use, along with the overrides in case that might help. 

It won't affect me too much if this doesn't get solved. As the main reason I need VanillaFix in the pack is for my brother to play the game with me. He's got an older computer, saving up for a new one, and occasionally crashes. Thought this might be a good addition to the pack so he wouldn't have to wait 5-10 minutes to load into the game. But who knows, this might be an issue for others too. Anyway, thanks for your time and effort, I've used VanillaFix in the past for when I was on the move a lot and had to play on my 4-year-old laptop, safe to say I wouldn't have been able to play as much without the mod, cheers

[Semi-Serious-1.0.0.zip](https://github.com/DimensionalDevelopment/VanillaFix/files/4576114/Semi-Serious-1.0.0.zip)

https://pastebin.com/mMqXh7XE
https://pastebin.com/u9qYvdBH

**Comment by br1c** [comment]
From what I've read somewhere else, Malisis comes prebundled with something called Mixins and it's apparently incompatible with the newest version of Mixins, which I think VanillaFix uses. You'd likely need to use an older version of VanillaFix

**Comment by BoogieMonster1O1** [comment]
Check #265 and #296
