### ISSUE TITLE
paste.dimdev.org returns HTTP 502, breaking the "Get link" feature in VanillaFix

### ISSUE THREAD

**Issue by James103** [DimensionalDevelopment/VanillaFix#262]
This means that I'm unable to directly post the crash report from VanillaFix to the bug tracker of whatever mod(s) caused the crash, and instead I have to look for the crash report, copy and upload it, and then link it in the other mod, which takes much more time overall. 

This applies no matter if I use http or https to access the site, or whatever I use a browser or the VanillaFix mod itself to send the request.

**Comment by Umustalldie2** [comment]
Hey, this might actually be a dumb question and this probably isn't appropriate here, but how do you actually find the crash report?

**Comment by James103** [comment]
As a workaround, you can go into the `.minecraft` directory of the instance of Minecraft where the crash occurred (by default `%appdata%` with the vanilla launcher), go into the `crash-reports` folder, and find the relevant crash reports there.

**Comment by Macleykun** [comment]
Resolved. Went into the server and did some asking around. Thanks to the user Snowie the site: https://paste.dimdev.org is back-up again! Also all previously uploaded crashes are accessable again! Not the onces between now and when the site went down.
