### ISSUE TITLE
Crash on startup VanillaFix-1.0.10-150

### ISSUE THREAD

**Issue by bolte-io** [DimensionalDevelopment/VanillaFix#271]
When starting VanillaFix-1.0.10-150 with the Surge mod (2.0.77) it crashes, providing the following log:
[Log.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/4757251/Log.txt)
When removing Surge the game is able to load.

**Comment by ACGaming** [comment]
Update Surge to version 2.0.79 and try again.
