### ISSUE TITLE
Crash on startup (VanillaFix 1.0.10-150 + BetterPortals 0.3.7.7)

### ISSUE THREAD

**Issue by juliantcf** [DimensionalDevelopment/VanillaFix#280]
Running the latest 1.12.2 forge 2854. Only these two mods and the Forgelin-1.8.4 dependency installed, it boots me back to the launcher within seconds of pressing play. Likely a mixin issue, because the suggested fix (renaming the jar to "_VanillaFix") solves the problem. Seems you're already aware of this issue but the changelog says please report so here I am.

**Comment by Gliese-832-c** [comment]
The same happened with VanillaFix + Tinkers' Construct.

**Comment by NightOps007** [comment]
[mixin 0-7-0-8 compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility)
