### ISSUE TITLE
Incompatible with Salhack, Kami blue and Impact

### ISSUE THREAD

**Issue by ilan1009** [DimensionalDevelopment/VanillaFix#287]
Aight, Checked through all my mods list and it immediately crashes every time i have those in there.

**Comment by ilan1009** [comment]
edited

**Comment by ilan1009** [comment]
fixed...

**Comment by jimeral** [comment]
this also doesn't work with future either

**Comment by BoogieMonster1O1** [comment]
Update vanillafix to 1.0.10-150
If that doesnt work read the pinned issues (#296 and #265)
