### ISSUE TITLE
VanillaFix and Phosphor together cause immediate crash

### ISSUE THREAD

**Issue by sappykun** [DimensionalDevelopment/VanillaFix#288]
## Version of VanillaFix
>VanillaFix-1.0.10-99

## Have you verified this is an issue in the latest build
- [ ] Y
- [x] N
- [ ] N/A

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [ ] Y
- [x] N
- [ ] N/A

>[phosphor-forge-mc1.12.2-0.2.7-universal.jar](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge?comment=77)

## Crash report or log or visualVM (if applicable)

>[https://paste.ee/p/lWh3y](https://paste.ee/p/lWh3y)

## Description of the problem
When I launch Minecraft with both VanillaFix and Phosphor installed, I receive the traceback before Minecraft even has a chance to spawn a window.

Current workaround is to disable one mod and run Minecraft with the other one.  I'm running an Enigmatic 2 server, which comes with Phosphor, but I am not blocked by anything except running the two mods together.

It's worth noting that jellyquid no longer supports any of his Forge mods.

**Comment by EnderBro123** [comment]
Why'd he make the mods then. This mod's dead anyways so, fuck it.

**Comment by BoogieMonster1O1** [comment]
Phosphor isn’t required on the client when it’s on the server.
 This crash is probably caused due to different a mixin version which can’t be solved now as jellysquid no longer supports forge.

**Comment by BoogieMonster1O1** [comment]
> Why'd he make the mods then. This mod's dead anyways so, fuck it.

To know why jellysquid stopped supporting the forge versions of her mods, read [this](https://gist.github.com/jellysquid3/8b68b81a5e48462f8690284a0a3c89a1)

**Comment by Oct0bass** [comment]
@EnderBro123 Dude, come on.  This mod (assuming you mean VF) is not dead at all, if you payed attention you'd know that .  Also, people do sometimes stop working on things for whatever reason, and not making something in the first place because something might happen in the future to stop working on your mod is STUPID.  That logic doesn't work out at all. Modders do what they do because they want, and pleasing irritating people like you is not on their priority list.  Sometimes things work sometimes they don't, sometimes it can be fixed and sometimes not.  So saying rude things when something doesn't work is a stupid thing to do.

**Comment by NightOps007** [comment]
@Oct0bass I think he meant phosphor is dead. That mod's developer is no longer updating for forge, only fabric.

**Comment by BoogieMonster1O1** [comment]
@sappykun Update vanillafix to 1.0.10-150

**Comment by BoogieMonster1O1** [comment]
> @Oct0bass I think he meant phosphor is dead. That mod's developer is no longer updating for forge, only fabric. F.Y.I. I managed to run both phosphor and vanillafix once I added [mixin 0-7-0-8 compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility). Issue should probably be closed with this advise. Don't know which of the two mods is behind with mixin, but I would assume it's phosphor since it's no longer updating.

vanillafix 1.0.10-99 uses an older mixin version, hence it's the cause for incompatibility with phosphor, which uses the newest
