### ISSUE TITLE
Fabric (Request)

### ISSUE THREAD

**Issue by Gomez96** [DimensionalDevelopment/VanillaFix#293]
Can you please make fabric 1.16.2? I use many great mods, but some of them are making lags even though I have good computer for games and I use other mods that reduce lags. I'll understand, if you don't wanna port your mod to Fabric, but I'd highly appreciate it and be very grateful for that.

**Comment by BoogieMonster1O1** [comment]
> Can you please make fabric 1.16.2? I use many great mods, but some of them are making lags even though I have good computer for games and I use other mods that reduce lags. I'll understand, if you don't wanna port your mod to Fabric, but I'd highly appreciate it and be very grateful for that.

The devs have expressed thoughts about porting vanillafix to fabric. Not sure if there's a port underway. 

Not Enough Crashes has the better crashes feature (https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes)

**Comment by BoogieMonster1O1** [comment]
VanillaFix has been (mostly) ported. Check the 1.16 branch.
