### ISSUE TITLE
Client crash with VanillaFix

### ISSUE THREAD

**Issue by Johnny2111** [DimensionalDevelopment/VanillaFix#294]
Hello.  this issue is relevant for the latest version of VanillaFix.  When I start the client, the message "Unexpected error has occurred" appears.  not even a loading screen.  for example: Project ozone 3 starts with this version, but Omnifactory does not. Probably this is due to incompatibilitiy
[latest (1).log](https://github.com/DimensionalDevelopment/VanillaFix/files/5342465/latest.1.log)

**Comment by youdontknowmyname** [comment]
do you have optifine?

**Comment by youdontknowmyname** [comment]
if so, you might need to remove it

**Comment by BoogieMonster1O1** [comment]
Read the pinned issues (#296 and #265)
