### ISSUE TITLE
vannila fix crashes at start up

### ISSUE THREAD

**Issue by Milky435** [DimensionalDevelopment/VanillaFix#298]
it says a unknown mod crashes the game but when i remove vannila fix it doesnt crash
crash report vvv

---- Minecraft Crash Report ----
// You're mean.

Time: 2020-10-27 13:50:08 AEDT
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1131)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 472768856 bytes (450 MB) / 1073741824 bytes (1024 MB) up to 5368709120 bytes (5120 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 49 mods loaded, 49 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                  | Version                     | Source                                            | Signature                                |
       |:----- |:------------------- |:--------------------------- |:------------------------------------------------- |:---------------------------------------- |
       | L     | minecraft           | 1.12.2                      | minecraft.jar                                     | None                                     |
       | L     | mcp                 | 9.42                        | minecraft.jar                                     | None                                     |
       | L     | FML                 | 8.0.99.99                   | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | forge               | 14.23.5.2854                | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | creativecoredummy   | 1.0.0                       | minecraft.jar                                     | None                                     |
       | L     | itemphysic          | 1.4.0                       | minecraft.jar                                     | None                                     |
       | L     | micdoodlecore       |                             | minecraft.jar                                     | None                                     |
       | L     | voxelmap            | 1.9.10                      | VoxelMap-Mod-1.12.2.jar                           | None                                     |
       | L     | alcatrazcore        | 1.0.4                       | alcatrazcore-1.0.4.jar                            | None                                     |
       | L     | ambience            | GRADLE:VERSION-GRADLE:BUILD | Ambience+1.1-10.jar                               | None                                     |
       | L     | atlcraft            | MC1.12-Ver1.9               | ATLCraftCandlesMod(MC1.12-Ver1.9).jar             | None                                     |
       | L     | jei                 | 4.16.1.301                  | jei_1.12.2-4.16.1.301.jar                         | None                                     |
       | L     | quark               | r1.6-178                    | Quark-r1.6-178.jar                                | None                                     |
       | L     | autoreglib          | 1.3-32                      | AutoRegLib-1.3-32.jar                             | None                                     |
       | L     | better_diving       | 1.5.8                       | BetterDiving-1.12.2-1.5.8.jar                     | None                                     |
       | L     | forgelin            | 1.8.4                       | Forgelin-1.8.4.jar                                | None                                     |
       | L     | betterfoliage       | 2.2.0                       | BetterFoliage-MC1.12-2.2.0.jar                    | None                                     |
       | L     | cakechomps          | 1.12.2-1.0                  | cakechomps-1.12.2-1.0.jar                         | None                                     |
       | L     | chunkanimator       | 1.2                         | ChunkAnimator-MC1.12-1.2.jar                      | None                                     |
       | L     | classiccombat       | 1.0.1                       | ClassicCombat-1.0.1.jar                           | None                                     |
       | L     | creativecore        | 1.10.0                      | CreativeCore_v1.10.32_mc1.12.2.jar                | None                                     |
       | L     | galacticraftcore    | 4.0.2.280                   | GalacticraftCore-1.12.2-4.0.2.280.jar             | None                                     |
       | L     | orelib              | 3.6.0.1                     | OreLib-1.12.2-3.6.0.1.jar                         | None                                     |
       | L     | dsurround           | 3.6.1.0                     | DynamicSurroundings-1.12.2-3.6.1.0.jar            | None                                     |
       | L     | dynamictrees        | 1.12.2-0.9.18               | DynamicTrees-1.12.2-0.9.18.jar                    | None                                     |
       | L     | enhancedvisuals     | 1.3.0                       | EnhancedVisuals_v1.3.18_mc1.12.2.jar              | None                                     |
       | L     | galacticraftplanets | 4.0.2.280                   | Galacticraft-Planets-1.12.2-4.0.2.280.jar         | None                                     |
       | L     | mjrlegendslib       | 1.12.2-1.2.0                | MJRLegendsLib-1.12.2-1.2.0.jar                    | None                                     |
       | L     | extraplanets        | 1.12.2-0.7.0                | ExtraPlanets-1.12.2-0.7.0.jar                     | None                                     |
       | L     | fbp                 | 2.4.1                       | FancyBlockParticles-1.12.x-2.4.1.jar              | None                                     |
       | L     | cfm                 | 6.3.1                       | furniture-6.3.1-1.12.2.jar                        | None                                     |
       | L     | waila               | 1.8.26                      | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
       | L     | ichunutil           | 7.2.2                       | iChun-Util-Mod-1.12.2.jar                         | None                                     |
       | L     | jmc                 | 1.1                         | JustMoreCakes-2.0_MC1.12.2.jar                    | None                                     |
       | L     | kleeslabs           | 5.4.11                      | KleeSlabs_1.12.2-5.4.11.jar                       | None                                     |
       | L     | mobdismemberment    | 7.0.0                       | MobDismemberment-1.12.2-7.0.0.jar                 | None                                     |
       | L     | morph               | 7.2.0                       | Morphing-Mod-1.12.2.jar                           | None                                     |
       | L     | mutantbeasts        | 1.12.2-1.0.1                | MutantBeasts-1.12.2-1.0.1.jar                     | None                                     |
       | L     | mw                  | 0.4.4.6                     | mw_2.0-0.4.4.6_mc1.12.2.jar                       | None                                     |
       | L     | pdp                 | 1.12.2-1.2.4                | ProportionalDestructionParticles-1.12.2-1.2.4.jar | None                                     |
       | L     | quarkoddities       | 1                           | QuarkOddities-1.12.2.jar                          | None                                     |
       | L     | randomtweaks        | 1.12.2-2.8.2.0              | randomtweaks-1.12.2-2.8.2.0.jar                   | None                                     |
       | L     | skyes_bakery        | 2.1.1                       | Skye's+Bakery+2.1.1+for+MC1.12.2.jar              | None                                     |
       | L     | soundfilters        | 0.12.1_for_1.12             | SoundFilters-0.12.1_for_1.12.jar                  | None                                     |
       | L     | spiderstpo          | 1.0.3                       | spiders-2.0-1.12.2-1.0.3.jar                      | None                                     |
       | L     | tetra               | 0.39.1                      | tetra-1.12.2-0.39.1.jar                           | None                                     |
       | L     | vanillafix          | 1.0.10-SNAPSHOT             | VanillaFix-1.0.10-99.jar                          | None                                     |
       | L     | wawla               | 2.5.273                     | Wawla-1.12.2-2.5.273.jar                          | None                                     |
       | L     | wearablebackpacks   | 3.1.4                       | WearableBackpacks-1.12.2-3.1.4.jar                | None                                     |
  Loaded coremods (and transformers): TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      Quark Plugin (Quark-r1.6-178.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.32_mc1.12.2.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.33_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      SCFMLCorePlugin (StalkerCreepers-1.12.1.jar)
                                        atomicstryker.stalkercreepers.common.SCTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
                                        com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: 1.12.2-forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 1.12.zip, pmc-mob-pack-squid_mcfries-turn-it-the-other-way-.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz

**Comment by BoogieMonster1O1** [comment]
Update vanillafix

**Comment by Milky435** [comment]
> Update vanillafix

works now
