### ISSUE TITLE
Vanilla Fix won't work.

### ISSUE THREAD

**Issue by Dibowac123414** [DimensionalDevelopment/VanillaFix#299]
I tried having Mixing and Vanilla Fix In my Mod Folder, but for some reason It doesn't seem to be working properly or as Intended.
[10-11-2020_03_45.]

**Comment by BoogieMonster1O1** [comment]
Can you send the log?

**Comment by Dibowac123414** [comment]
> Can you send the log?

I meant Mixin not Mixing. 
Also I can't find any crash log from today.

Also VanillaFix won't Install at all for whatever reason.
[10-11-2020_08_16.]

**Comment by BoogieMonster1O1** [comment]
remove mixin from your mods folder, run the game again, and send the crash report here.

**Comment by Dibowac123414** [comment]
> remove mixin from your mods folder, run the game again, and send the crash report here. [10-11-2020_10_53_10_52.]

I can't find a crash report for today but I do have of yesterday. And a launcher log and something from the log folder.
[2020-11-10-1.log](https://github.com/DimensionalDevelopment/VanillaFix/files/5516330/2020-11-10-1.log) [Log Folder.]

[Launcher Log.] 
[launcher_log.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/5516344/launcher_log.txt)

[crash-2020-11-09_08.47.33-client.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/5516350/crash-2020-11-09_08.47.33-client.txt)

**Comment by BoogieMonster1O1** [comment]
there's not much i can do to help without a crash report
run the game, let it crash, and send the newest file in the crash reports folder here

**Comment by Dibowac123414** [comment]
> there's not much i can do to help without a crash report
> run the game, let it crash, and send the newest file in the crash reports folder here

I was running the game but got a Service System Exception BSOD Instead.
I also have Forge, Optiforge and Optifine In my mod folder, could those mods be conflicting with VanillaFix?".
[11-11-2020_02_33.]

**Comment by BoogieMonster1O1** [comment]
> > there's not much i can do to help without a crash report
> > run the game, let it crash, and send the newest file in the crash reports folder here
> 
> I was running the game but got a Service System Exception BSOD Instead.
> I also have Forge, Optiforge and Optifine In my mod folder, could those mods be conflicting with VanillaFix?".
> [11-11-2020_02_33.]

This mod is for 1.12.2 and optiforge is only supported on newer versions. Are you sure you're using 1.12.2?

**Comment by ainlzj** [comment]
I did the same, but only the most original error report
[minecraft-exported-logs-2020-11-23T18-29-26.log](https://github.com/DimensionalDevelopment/VanillaFix/files/5582270/minecraft-exported-logs-2020-11-23T18-29-26.log)

**Comment by BoogieMonster1O1** [comment]
another mixin error eh

see #265 and #296

so either rename `VanillaFix-1.0.10-150.jar` to `_VanillaFix-1.0.10-150.jar` or install the mod linked in #296
