### ISSUE TITLE
Crashed with Valkyrien Skies

### ISSUE THREAD

**Issue by Determancer** [DimensionalDevelopment/VanillaFix#303]
Valkyrien Skies may use an outdated Mixins version, and running it with Vanilla Fix 1.0.10-150 crashes the game, just as the warning described.
So I report the issue as changelog instructed.
Launcher: HMCL
Forge Version: 2854
[crash-2020-12-06_00.59.46-client.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/5648452/crash-2020-12-06_00.59.46-client.txt)
############################
Adding a character to make Vanilla Fix load ahead of Valkyrien Skies can solve the crash problem.
The test was done in a pack that only contained Vanilla Fix and Valkyrien Skies.

**Comment by BoogieMonster1O1** [comment]
check the pinned issues. there's two ways to fix it
