### ISSUE TITLE
Mod doesn't work.

### ISSUE THREAD

**Issue by notBartik** [DimensionalDevelopment/VanillaFix#304]
I have a little problem. It may be, that I'm just a stupid fish, but my game just ignores VanillaFix. I have put the file to the 'mods' folder, but when I start the game, there is no VanillaFix in the mods tab. Maybe someone know how to fix this?

Forgot to say: I'm on 1.16.4 and I use other mods.

**Comment by dominic-03** [comment]
VanillaFix is not compatible with 1.16.4, sorry.
