### ISSUE TITLE
cant not start the game with vannilaFix 

### ISSUE THREAD

**Issue by AlphaBuzz** [DimensionalDevelopment/VanillaFix#311]
When I click play the game said "an uknow issuse" and the game crashes and when I disable the vannila fix its ok and odnt crash

Mods:
⛄ Snow! Real Magic!
Snownee_
SnowRealMagic-0.3.3.jar
AbyssalCraft
Shinoow
AbyssalCraft-1.12.2-1.10.3.jar
Actually Additions
Ellpeck
ActuallyAdditions-1.12.2-r152.jar
Additional Structures
XxRexRaptorxX
Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar
Aether Continuation
raptor4694
Aether Continuation v1.3.0.jar
Aether: Lost Content
ModdingLegacy
lost-aether-content-1.12.2-1.0.2.jar
AppleSkin
squeek502
AppleSkin-mc1.12-1.0.14.jar
Applied Energistics 2
AlgorithmX2
appliedenergistics2-rv6-stable-7.jar
Aquaculture 2
Shadowclaimer
Aquaculture-1.12.2-1.6.8.jar
Baubles
Azanor13
Baubles-1.12-1.5.2.jar
BetterFps
Guichaguri
BetterFps-1.4.8.jar
BiblioCraft
Nuchaz
BiblioCraft[v2.4.5][MC1.12.2].jar
Bibliotheca
EwyBoy
bibliotheca-1.3.6-1.12.2.jar
Biomes O' Plenty
Forstride
BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar
Blood Magic
WayofTime
BloodMagic-1.12.2-2.4.3-105.jar
Bonsai Trees 2
davenonymous
bonsaitrees-1.1.4-b170.jar
Bookshelf
DarkhaxDev
Bookshelf-1.12.2-2.3.590.jar
Botania
Vazkii
Botania r1.10-363.jar
Buildcraft
Covert_Jaguar
buildcraft-all-7.99.24.8.jar
Chameleon
Texelsaur
Chameleon-1.12-4.1.3.jar
Chisel
tterrag1098
Chisel-MC1.12.2-1.0.2.45.jar
Chisels & Bits
AlgorithmX2
chiselsandbits-14.33.jar
CodeChicken Lib 1.8.+
covers1624
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFH Core
TeamCoFH
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFH World
TeamCoFH
CoFHWorld-1.12.2-1.4.0.1-universal.jar
Comforts (Forge)
TheIllusiveC4
comforts-1.12.2-1.4.1.3.jar
ConnectedTexturesMod
tterrag1098
CTM-MC1.12.2-1.0.2.31.jar
Construct's Armory
TheIllusiveC4
conarm-1.12.2-1.2.5.10.jar
Cucumber Library
BlakeBr0
Cucumber-1.12.2-1.1.3.jar
Cyclops Core
kroeser
CyclopsCore-1.12.2-1.6.7.jar
Dark Utilities
DarkhaxDev
DarkUtils-1.12.2-1.8.230.jar
Ender IO
CrazyPants_MC
EnderIO-1.12.2-5.2.66.jar
EnderCore
tterrag1098
EnderCore-1.12.2-0.5.76.jar
Equivalent Energistics
Mordenkainen3141
EquivalentEnergistics-1.12.2-PE_1.3.1B-AE2_RV6-0.8.3.jar
EvilCraft
kroeser
EvilCraft-1.12.2-0.10.78.jar
Extra Rails
ShadowfactsDev
ExtraRails-1.12-1.3.0.jar
Extra Utilities
Forge_User_06804776
extrautils2-1.12-1.9.9.jar
Extreme Reactors
ZeroNoRyouki
ExtremeReactors-1.12.2-0.4.5.68.jar
Fast Leaf Decay
olafskiii
FastLeafDecay-v14.jar
Floating Rails
EwyBoy
Floating-Rails-2.0.3-1.12.2.jar
Forestry
_ForgeUser7678633
forestry_1.12.2-5.8.2.387.jar
Forge MultiPart CBE
covers1624
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
Guide-API
TehNut
Guide-API-1.12-2.1.8-63.jar
Hwyla
TehNut
Hwyla-1.8.26-B41_1.12.2.jar
Ice and Fire: Dragons
alex1the1666
iceandfire-1.9.1-1.12.2.jar
Industrial Craft
sfPlayer1
industrialcraft-2-2.8.170-ex112.jar
Inventory Pets
Purplicious_Cow_
inventorypets-1.12-2.0.12.jar
Iron Backpacks
gr8pefish
IronBackpacks-1.12.2-3.0.8-12.jar
Iron Chests
ProgWML6
ironchest-1.12.2-7.0.72.847.jar
JourneyMap
techbrew
journeymap-1.12.2-5.7.1.jar
Just Enough Items (JEI)
mezz
jei_1.12.2-4.16.1.301.jar
Just Enough Resources (JER)
way2muchnoise
JustEnoughResources-1.12.2-0.9.2.60.jar
LLibrary
_ForgeUser11902522
llibrary-1.7.20-1.12.2.jar
Macaw's Windows
sketch_macaw
mcw-windows-1.0.0-mc1.12.2.jar
Magic Bees
MysteriousAges
MagicBees-1.12.2-3.1.10.jar
MalisisCore
Ordinastie
malisiscore-1.12.2-6.5.1.jar
MalisisDoors
Ordinastie
malisisdoors-1.12.2-7.3.0.jar
Mantle
mDiyo
Mantle-1.12-1.3.3.55.jar
Mekanism
bradyaidanc
Mekanism-1.12.2-9.8.3.390.jar
Mekanism Generators
bradyaidanc
MekanismGenerators-1.12.2-9.8.3.390.jar
Mekanism Tools
bradyaidanc
MekanismTools-1.12.2-9.8.3.390.jar
MekanismOres
phantamanta44
mekores-2.0.13.jar
MineColonies
H3lay
minecolonies-1.12.2-0.11.804-RELEASE-universal.jar
More Overlays
FeldiM245
moreoverlays-1.15.1-mc1.12.2.jar
Mouse Tweaks
YaLTeR
MouseTweaks-2.10-mc1.12.2.jar
MrTJPCore
MrTJP
MrTJPCore-1.12.2-2.1.4.43-universal.jar
Mystical Agradditions
BlakeBr0
MysticalAgradditions-1.12.2-1.3.2.jar
Mystical Agriculture
BlakeBr0
MysticalAgriculture-1.12.2-1.7.5.jar
Nature's Compass
Chaosyr
NaturesCompass-1.12.2-1.8.5.jar
Neat
Vazkii
Neat 1.4-17.jar
Netherending Ores
ic_trab
Netherending-Ores-1.12.2-1.4.2.jar
OpenComputers
Sangar_
OpenComputers-MC1.12.2-1.7.5.192.jar
Pam's HarvestCraft
pamharvestcraft
Pam's HarvestCraft 1.12.2zg.jar
Patchouli
Vazkii
Patchouli-1.0-23.6.jar
Project Red - Base
MrTJP
ProjectRed-1.12.2-4.9.4.120-Base.jar
Project Red - Compat
MrTJP
ProjectRed-1.12.2-4.9.4.120-compat.jar
Project Red - Fabrication
MrTJP
ProjectRed-1.12.2-4.9.4.120-fabrication.jar
Project Red - Integration
MrTJP
ProjectRed-1.12.2-4.9.4.120-integration.jar
Project Red - Lighting
MrTJP
ProjectRed-1.12.2-4.9.4.120-lighting.jar
Project Red - Mechanical
MrTJP
ProjectRed-1.12.2-4.9.4.120-mechanical.jar
Project Red - World
MrTJP
ProjectRed-1.12.2-4.9.4.120-world.jar
ProjectE
SinKillerJ
ProjectE-1.12.2-PE1.4.1.jar
Railcraft
Covert_Jaguar
railcraft-12.0.0.jar
Redstone Arsenal
TeamCoFH
RedstoneArsenal-1.12.2-2.6.6.1-universal.jar
Redstone Flux
TeamCoFH
RedstoneFlux-1.12-2.1.1.1-universal.jar
Redstone Paste
FyberOptic
redstonepaste-mc1.12-1.7.5.jar
Security Craft
Geforce132
[1.12.2] SecurityCraft v1.8.21.jar
Shadowfacts' Forgelin
ShadowfactsDev
Forgelin-1.8.4.jar
ShadowMC
ShadowfactsDev
ShadowMC-1.12-3.8.0.jar
Storage Drawers
Texelsaur
StorageDrawers-1.12.2-5.4.2.jar
SwingThroughGrass
exidex
stg-1.12.2-1.2.3.jar
Thaumcraft
Azanor13
Thaumcraft-1.12.2-6.1.BETA26.jar
The Aether
GildedGames
aether-1.12.2-v1.5.3.1.jar
The Aether II
GildedGames
aether_ii-1.12.2-0.3.0+build411-universal.jar
The Twilight Forest
Benimatic
twilightforest-1.12.2-3.11.1021-universal.jar
Thermal Cultivation
TeamCoFH
ThermalCultivation-1.12.2-0.3.6.1-universal.jar
Thermal Dynamics
TeamCoFH
ThermalDynamics-1.12.2-2.5.6.1-universal.jar
Thermal Expansion
TeamCoFH
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
Thermal Foundation
TeamCoFH
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
Thermal Innovation
TeamCoFH
ThermalInnovation-1.12.2-0.3.6.1-universal.jar
Tinkers Construct
mDiyo
TConstruct-1.12.2-2.13.0.183.jar
Tinkers' Complement
KnightMiner
TinkersComplement-1.12.2-0.4.3.jar
U Team Core
HyCraftHD
u_team_core-1.12.2-2.2.5.147.jar
Underwater Rails
hennamann99
underwaterrails-1.0.0-universal.jar
Useful Railroads
HyCraftHD
useful_railroads-1.12.2-1.1.3.24.jar
VanillaFix
Runemoro
VanillaFix-1.0.10-150.jar
ViesCraft - Airships!
Vies
ViesCraft-1.12.2-5.9.16.jar
Water Strainer
Ruuubi
WaterStrainer-1.12-3.3.0.jar
Wireless Redstone CBE
covers1624
WR-CBE-1.12.2-2.3.2.33-universal.jar
XL Food Mod
mariot7
XL-Food-Mod-1.12.2-1.9.2.jar
ZeroCore 2

**Comment by Apogee0** [comment]
Yeah it happened to me too. 
When i remove the malisis door/core mod game started. try this maybe it will work.

**Comment by BoogieMonster1O1** [comment]
Check the pinned issues. There’s solutions on how to fix this
