### ISSUE TITLE
Crash With MixinBootstrap mod (1.12.2) (Forge: 2855)

### ISSUE THREAD

**Issue by KenyMylankca** [DimensionalDevelopment/VanillaFix#316]
https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap
with this mod + VanillaFix, it crashes. And when i turn B:modSupport=false, crash gets fixed.
[crash-2021-04-27_19.58.38-client.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/6386294/crash-2021-04-27_19.58.38-client.txt)

**Comment by Lucas559-noob** [comment]
but thats for 1.15+ not 1.12

**Comment by BoogieMonster1O1** [comment]
Update vanillafix

**Comment by Kasia1403** [comment]
> but thats for 1.15+ not 1.12

Forge 2855 is for MC 1.12.2, not 1.15+ !
