### ISSUE TITLE
Forge 1.16.5?

### ISSUE THREAD

**Issue by ChubbsWasTaken** [DimensionalDevelopment/VanillaFix#318]
Okay, so i have/use forge with quite a few mods. and i need alternatives to optifine that give good FPS but without being as bug-ridden as Chlorine is. is 1.16.5 forge planned? i really would love this mod in forge. 
Thanks.

**Comment by BoogieMonster1O1** [comment]
There are no plans for a forge 1.16 version
You might be interested in [this gist](https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88#forge-116). It has a list of other performance mods

**Comment by ChubbsWasTaken** [comment]
sad :(
