### ISSUE TITLE
strange behaviour with VanillaFix, MalisisDoors AND Level Up! Reloaded    (1.12.2)

### ISSUE THREAD

**Issue by Threydan** [DimensionalDevelopment/VanillaFix#320]
I know it's already a known issue that VanillaFix and MalisisDoors don't work well together because of Mixin stuff (not knowledged enough nor do i have the time to figure it out rn, plus i do know how to fix it so that is fine).
What i feel like is extremely strange is that if you have VanillaFix, MalisisDoors and Level Up! Reloaded installed, it works.
I might only have a little programming knowledge, but I hope that someone can explain what's going on, and that this might've been usefull in some way.

Steps to recreate/observe
1. Install VanillaFix
2. Install MalisisCore
3. Launch game (should crash with exit code: 0)
4. Install Level Up! Reloaded
5. Launch game (should run fine)

**Comment by BoogieMonster1O1** [comment]
Check the pinned issues, there’s solutions on how to fix this
