### ISSUE TITLE
Incompatibility with f5fix

### ISSUE THREAD

**Issue by zsn741656478** [DimensionalDevelopment/VanillaFix#33]
http://paste.ubuntu.org.cn/4331711
I can't start my client.

**Comment by ZombieHDGaming** [comment]
Never had this issue nor does it seem to happen with anyone else. What kind of system are you running? Is that in the default vanilla launcher? And possibly a mod list would be helpful.

**Comment by zsn741656478** [comment]
Oh. I know what's happen.
This mod and f5fix mod has clash
https://minecraft.curseforge.com/projects/third-person-camera-fix

**Comment by ZombieHDGaming** [comment]
Hmm, interesting. Since this mod is aimed at fixing Vanilla bugs/issues, we can look into adapting the fix into VanillaFix so you don't have to worry about a conflict. Should be pretty straight forward.

**Comment by zsn741656478** [comment]
OK. Thanks.

**Comment by ZombieHDGaming** [comment]
Fixed in latest dev build.
