### ISSUE TITLE
Mod lies to you!

### ISSUE THREAD

**Issue by xroblox33YouTube** [DimensionalDevelopment/VanillaFix#330]
When I'm in a void world with a modded skyblock my game crashes without a crash report and sends me back to launcher! so much for sending you to main menu! The people who said this are scumbags! ---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_21.17.2_Forge_1.12.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

/
Time: 11/17/21 4:51 PM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:45)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94)
	at net.minecraft.world.gen.ChunkGeneratorFlat.func_185931_b(ChunkGeneratorFlat.java:181)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:226)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:45)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94)
	at net.minecraft.world.gen.ChunkGeneratorFlat.func_185931_b(ChunkGeneratorFlat.java:181)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:226)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: Skyblock
	All players: 1 total; [EntityPlayerMP['EJbubaroni'/85, l='Skyblock', x=-2337.83, y=58.60, z=-592.79]]
	Chunk stats: ServerChunkCache: 1466 Drop: 0
	Level seed: 980139254848044680
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:air;1;village,biome_1,decoration,stronghold,mineshaft,lake,lava_lake,dungeon
	Level spawn location: World: (-1231,75,-479), Chunk: (at 1,4,1 in -77,-30; contains blocks -1232,0,-480 to -1217,255,-465), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Level time: 164696 game time, 164696 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 84758 (now: false), thunder time: 28881 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 564629200 bytes (538 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version                 | Source                                           | Signature                                |
	|:------ |:------------------------- |:----------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft                 | 1.12.2                  | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                       | 9.42                    | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                       | 8.0.99.99               | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                     | 14.23.5.2855            | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit                 | 1.3.3-1.12              | minecraft.jar                                    | None                                     |
	| LCHIJA | xaerominimap_core         | 1.12.2-1.0              | minecraft.jar                                    | None                                     |
	| LCHIJA | animalium                 | 0.3.8                   | Animalium-0.3.8.jar                              | None                                     |
	| LCHIJA | bettermobgriefinggamerule | 1.12.2-7.0.1            | bettermobgriefinggamerule-1.12.2-7.0.1.jar       | None                                     |
	| LCHIJA | geckolib3                 | 3.0.0                   | geckolib-forge-1.12.2-3.0.9.jar                  | None                                     |
	| LCHIJA | cqrepoured                | 2.5.3B                  | Chocolate_Quest_Repoured-1.12.2-2.5.3B.jar       | None                                     |
	| LCHIJA | extendedrenderer          | v1.0                    | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LCHIJA | coroutil                  | 1.12.1-1.2.37           | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LCHIJA | configmod                 | v1.0                    | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LCHIJA | craftstudioapi            | 1.0.0                   | CraftStudio-1.0.0.93-mc1.12-alpha.jar            | None                                     |
	| LCHIJA | customnpcs                | 1.12                    | CustomNPCs_1.12.2-(05Jul20).jar                  | None                                     |
	| LCHIJA | cyclopscore               | 0.11.11                 | CyclopsCore-1.12.2-0.11.11.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | dldungeonsjbg             | 1.14.8                  | DoomlikeDungeons-1.14.8-MC1.12.2.jar             | None                                     |
	| LCHIJA | gottschcore               | 1.14.0                  | GottschCore-mc1.12.2-f14.23.5.2854-v1.14.0.jar   | None                                     |
	| LCHIJA | dungeons2                 | 1.7.5                   | Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.5.jar      | None                                     |
	| LCHIJA | dungeontactics            | DT-0.16.9               | DungeonTactics-1.12.2-0.16.9.jar                 | None                                     |
	| LCHIJA | ageofabyssalcraft         | 0.7                     | Engender+Mod-1.12.2-0.7-pre1.jar                 | None                                     |
	| LCHIJA | ageofchaos                | 0.7                     | Engender+Mod-1.12.2-0.7-pre1.jar                 | None                                     |
	| LCHIJA | ageofminecraft            | 0.7                     | Engender+Mod-1.12.2-0.7-pre1.jar                 | None                                     |
	| LCHIJA | epicsiegemod              | 13.167                  | EpicSiegeMod-13.167.jar                          | None                                     |
	| LCHIJA | evilcraft                 | 0.10.54                 | EvilCraft-1.12.2-0.10.54.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | evilcraftcompat           | 1.0.0                   | EvilCraft-1.12.2-0.10.54.jar                     | None                                     |
	| LCHIJA | llibrary                  | 1.7.20                  | llibrary-1.7.20-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                | 1.9.1                   | iceandfire-1.9.1-1.12.2.jar                      | None                                     |
	| LCHIJA | journeymap                | 1.12.2-5.7.0            | journeymap-1.12.2-5.7.0.jar                      | None                                     |
	| LCHIJA | mocreatures               | 12.0.5                  | Mo-Creatures-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | mob_mash                  | 2.4                     | Mob+Mash-2.4.jar                                 | None                                     |
	| LCHIJA | monsterswarm              | 2.0.1                   | MonsterSwarm-2.0.1.jar                           | None                                     |
	| LCHIJA | raiders                   | 3.0.9                   | raiders-1.12.2-3.0.9.jar                         | None                                     |
	| LCHIJA | reccomplex                | 1.4.8.2                 | RecurrentComplex-1.4.8.2.jar                     | None                                     |
	| LCHIJA | additionalstructures      | 2.4.1                   | Rex's-Additional-Structures-1.12.x-(v.2.4.1).jar | None                                     |
	| LCHIJA | roguelike                 | 1.8.0                   | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| LCHIJA | roughmobsrevamped         | 2.3.21                  | roughmobsrevamped-1.12.2-2.3.21.jar              | None                                     |
	| LCHIJA | ruins                     | 17.1                    | Ruins-1.12.2.jar                                 | None                                     |
	| LCHIJA | savemystronghold          | 1.12.2-1.0.0            | savemystronghold-1.12.2-1.0.0.jar                | None                                     |
	| LCHIJA | sereneseasons             | 1.2.18                  | SereneSeasons-1.12.2-1.2.18-universal.jar        | None                                     |
	| LCHIJA | snowaccumulation          | 1.0.0                   | SnowAccumulation-1.12-1.0.0.jar                  | None                                     |
	| LCHIJA | tickratechanger           | 1.0.14                  | TickrateChanger-1.0.14.jar                       | None                                     |
	| LCHIJA | torchmaster               | 1.8.4.84                | torchmaster_1.12.2-1.8.4.84.jar                  | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCHIJA | torohealthmod             | 1.12.2-11               | torohealth-1.12.2-11.jar                         | None                                     |
	| LCHIJA | weather2                  | 1.12.1-2.6.12           | weather2-1.12.1-2.6.12.jar                       | None                                     |
	| LCHIJA | wrd                       | 0.8.0                   | Wesley's+Roguelike+Dungeons+V0.8.1.jar           | None                                     |
	| LCHIJA | worldedit                 | 6.1.10                  | worldedit-forge-mc1.12.2-6.1.10-dist.jar         | None                                     |
	| LCHIJA | xaerominimap              | 21.17.2                 | Xaeros_Minimap_21.17.2_Forge_1.12.jar            | None                                     |
	| LCHIJA | zombieawareness           | 1.12.1-1.11.16          | zombieawareness-1.12.1-1.11.16.jar               | None                                     |
	| LCHIJA | jurassicraft              | 2.1.23                  | JurassiCraft-1.12.2-2.1.23.jar                   | None                                     |
	| LCHIJA | structurize               | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar          | None                                     |
	| LCHIJA | minecolonies              | 1.12.2-0.11.841-ALPHA   | minecolonies-1.12.2-0.11.841-ALPHA-universal.jar | None                                     |
[crash-2021-11-17_16.51.06-server.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/7566524/crash-2021-11-17_16.51.06-server.txt)

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_21.17.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['EJbubaroni'/85, l='Skyblock', x=-2337.83, y=58.60, z=-592.79]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 16
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Enhanced Default v1.12.zip
	OpenGlVersion: 4.6.148201 Compatibility Profile Context 20.50.02.11 27.20.15002.11002
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by ZombieHDGaming** [comment]
Hi there. I don't normally reply to these issues anymore as I'm busy with real life, but since you decided to call me and Rune scumbags, I felt this needed a personal touch.

First of all, you call us scumbags, you have never even talked with the DimDev team, so obviously you have no idea what the hell you're talking about. Second of all, you call us scumbags for a feature we display proudly on the mod page that we worked hard to make sure users like you were able to enjoy it. Your log clearly shows you don't have the mod installed, so please take your comments elsewhere if you really feel like we deserve the hate when you can't properly install a mod.

Thank you and goodbye.

**Comment by darkheadmaster132** [comment]
" I don't normally reply to these issues anymore" then set the mod to abandoned then ppl won't call you scumbag anymore
