### ISSUE TITLE
tengo un problema con mi skin de minecraft

### ISSUE THREAD

**Issue by FranKing278** [DimensionalDevelopment/VanillaFix#331]
hola disculpa tengo un problema con mi skin, uso minecraft tlauncher y tengo un modpack, pero a la hora de poner el mod mi skin es remplazada por la de steve. me gustaría saber porque pasa esto.

**Comment by ZombieHDGaming** [comment]
Simple, don't use TLauncher. They are violating the EULA by what they offer and we don't support it.
