### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Eddi2015** [DimensionalDevelopment/VanillaFix#34]

**Comment by Hypsellis** [comment]
I would suggest to merge foamfix stuff too. ;)

**Comment by Rongmario** [comment]
I'd keep Foamfix separate. As asie still maintains his mods.

**Comment by TheSnowyChickens** [comment]
The "better FPS" creator has no time to work on it, so he telled it us under some issues and other places.

**Comment by JosEffigy** [comment]
Upvote. except on that math thing. It is reported to lower performance to other users including me. Unless you can optimize the code that betterFPS runs.

**Comment by ghost** [comment]
.

**Comment by Eddi2015** [comment]
.
