### ISSUE TITLE
Skin bug

### ISSUE THREAD

**Issue by Ayanowo** [DimensionalDevelopment/VanillaFix#348]
I use tlauncher to play minecraft and for some reason,the mod just removes my skin in version 1.12.2
Someone nows something about?

**Comment by Iohannes562** [comment]
Same issue, I was hopping someone found a solution.

**Comment by ZombieHDGaming** [comment]
As mentioned in all the other issues relating to "skin issues," TLauncher is not supporter due to the fact that it blantly goes against the EULA. Used outside TLauncher does show skins just fine.
