### ISSUE TITLE
Shift.BY=2 exceeds the maximum allowed value 0

### ISSUE THREAD

**Issue by Eddi2015** [DimensionalDevelopment/VanillaFix#35]
I fired up MC (with some mods szch as VF, FoamFix, Optifine, FancyBlockParticles) and got this warning in the main menu (only once): `[18:38:00] [main/WARN] [mixin]: @Inject(@At("INVOKE")) Shift.BY=2 on mixins.vanillafix.textures.json:client.MixinRenderChunk::handler$initCompiledChunk$zbc000 exceeds the maximum allowed value 0. Increase the value of maxShiftBy to suppress this warning.`

Not sure if this helps somehow :P

**Comment by ZombieHDGaming** [comment]
Just ignore it, it's just a warning about something we do.

**Comment by Runemoro** [comment]
I saw that. `maxShiftBy` is there, but Mixin seems to be ignoring it for some reason.

**Comment by Runemoro** [comment]
https://github.com/SpongePowered/Mixin/issues/265

**Comment by Runemoro** [comment]
Fixed by Mixin.
