### ISSUE TITLE
Botania error while trying to make Terrasteel Ingots

### ISSUE THREAD

**Issue by NightsBladeofTruth** [DimensionalDevelopment/VanillaFix#37]
VanillaFix starts throwing up errors the moment the Terrestrial Agglomeration Plate is activated.

https://paste.dimdev.org/ifareveyeg.txt

The plate works fine without VFix.

**Comment by ZombieHDGaming** [comment]
That is an early warning from VF about what Botania is doing. It is a known issue and should be reported to the Botania repo.

**Comment by ZombieHDGaming** [comment]
**UPDATE:** It seems the issue has been fixed on Botania's side and will be fixed in the next release.

**Comment by Runemoro** [comment]
Not a VanillaFix bug, VanillaFix is just warning you about a problem in another mod.
