### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Kevadro** [DimensionalDevelopment/VanillaFix#43]
I can't start Minecraft beacause of a weird mixin related bug

[Pastebin](https://pastebin.com/kmHyQsi9)

**Comment by Kevadro** [comment]
I found that F5fix and vanillafix are incompatible, so removing any of the two solved the issue, so i removed F5fix

**Comment by Runemoro** [comment]
Yes, and VanillaFix also fixes the same bug fixed by F5fix, so you're not losing anything.
