### ISSUE TITLE
Issues 29 and 32 (fall damage) "partially resolved"

### ISSUE THREAD

**Issue by SextupleTap** [DimensionalDevelopment/VanillaFix#44]
The modification was tested in my modpack and in an isolated environment, not even Optifine was installed, only VanillaFix was installed on its own. I have even deleted the config files (I don't even know how that would help but I did delete them, and it did nothing).

I think that the bug was introduced in VanillaFix-1.0.4-35 and continues to persist to the current version of VanillaFix-1.0.6-53, all versions prior to VanillaFix-1.0.4-35 (VanillaFix-1.0.3-30 and under) did not have this bug.

The bug still occurs, but it seems to be a more uncommon occurrence, happening less often then the version(s) before.

However, at this point I just wonder if there is something stupid going on on my end.
Rundown of game specifications:
Mod version: VanillaFix-1.0.6-53
Forge Version: 1.12.2-forge1.12.2-14.23.3.2655
Java Arguments: `-Xmx4608M -Xms1536M -XX:+DisableExplicitGC -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M`

Edit:
I have upgraded to forge version Recommended 1.12.2 - 14.23.4.2703 and it is still the same.

**Comment by ddelaparte** [comment]
Also seeing this. Simply holding down jump while running across a flat map will occasionally do half a heart of fall damage.

**Comment by Mattabase** [comment]
This bug still exits in VanillaFix-1.0.7-56

Just running and jumping will cause it.

**Comment by Runemoro** [comment]
@Mattabase I'm not able to reproduce it. Can you upload a video? It is very unlikely that the bug still exists, since the fix makes the server not use the client's y position at all anymore.

**Comment by ZombieHDGaming** [comment]
@Mattabase The fix was included in 1.0.7-58, can you upgrade to that and see if it persists?

**Comment by Mattabase** [comment]
Oh, I did not see a 1.0.7-58 in the release section. Where would I find that build to test it?

**Comment by Runemoro** [comment]
@Mattabase The last few builds failed. The next build should be there.

**Comment by Mattabase** [comment]
Glad to hear it. This mod has become a must. This has saved me a silly amount of time while working on my Modpacks.

**Comment by Mattabase** [comment]
Any word on this bug?

**Comment by ZombieHDGaming** [comment]
We are trying to do some more tests on this bug since we *think* that we fixed most, if not all, of the bugs, but due to some issues that are out of our hands, our builds and build systems are being rather unkind and we are trying to figure out how to fix it. I believe it may be something to do with jitpack.io but it's still up in the air atm.

**Comment by ZombieHDGaming** [comment]
Okay, managed to fix our building system somehow.............the newest dev build is in the releases now with the major fixes. It looks like there is 1 minor bug we need to address with stairs, but it's not that major to worry about it for testing purposes. We'll try to fix it and get it ready for the next CurseForge release though.
