### ISSUE TITLE
[Bug] Fall-damage values wrong? Check videos inside this report.

### ISSUE THREAD

**Issue by Gbergz** [DimensionalDevelopment/VanillaFix#45]
Hello! I've started noticing that Fall-Damage values are wrong if you compare them to Regular Minecraft (Vanilla). Is this a bug/glitch you guys know about already? If so, sorry if this is a repost.

Check videos below:

This is the test without the Mod VanillaFix: (No damage applied like normal)
[https://streamable.com/qgvo2](https://streamable.com/qgvo2)

And this is the test WITH the Mod VanillaFix: (As you can see damage is applied)
[https://streamable.com/7do8y](https://streamable.com/7do8y)

**Comment by Runemoro** [comment]
Fall damage is meant to apply for all falls >3 blocks, but due to a vanilla bug, it is possible for vanilla to not apply damage if it is lagging. VanillaFix fixes this.

You jumped from 2 blocks high, so you fell around 3.5 blocks.
