### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by MokahTGS** [DimensionalDevelopment/VanillaFix#46]
Crash log: https://pastebin.com/YnykVs06

VanillaFix 1.0.6.53
Forge 2705

Rolling back to 1.0.5.43 fixes the crash.

Full mod list: https://pastebin.com/vFixUFy1

**Comment by Runemoro** [comment]
It seems to be incompatible with one of your other mods. Could you upload a full log?

**Comment by MokahTGS** [comment]
Full crash log is there along with mod list.

**Comment by Runemoro** [comment]
No, I need the `latest.log` and `debug.log` files that are in your "logs" folder, inside your Minecraft folder.

**Comment by MokahTGS** [comment]
https://www.dropbox.com/s/27fiosz04b2cvxq/logs.7z?dl=0

**Comment by Runemoro** [comment]
That's the wrong log. Minecraft doesn't seem to have crashed on the run those logs are from. Could you re-run Minecraft with 1.0.6 and then upload latest.log and debug.log?

**Comment by MokahTGS** [comment]
Updated Forge and it no longer crashes.

**Comment by Hypsellis** [comment]
I got the last Forge version, and it still crashes for me. https://pastebin.com/LD9hJUzP
