### ISSUE TITLE
Forge missing dependency screen crashes when Chisel is installed

### ISSUE THREAD

**Issue by DWX12** [DimensionalDevelopment/VanillaFix#48]
Minecraft:
1.12.2

Forge Version:
forge1.12.2-14.23.3.2702

Crash Report:
https://paste.dimdev.org/bumotiyobu.mccrash

[debug.log](https://github.com/DimensionalDevelopment/VanillaFix/files/2045637/debug.log)

[latest.log](https://github.com/DimensionalDevelopment/VanillaFix/files/2045638/latest.log)

**Comment by DWX12** [comment]
Believe it had something to do with a Thaumcraft draco aspect issue between Thaumic Additions and Ice and Fire as everything starts up just fine without Thaumic Additions. Don't know why it triggered anything with VanillaFix though.

**Comment by Robijnvogel** [comment]
duplicate of #46

**Comment by Robijnvogel** [comment]
@DWX12 apparently updating your Forge version should help.

@Runemoro even so, shouldn't VanillaFix work with about every Forge version? Especially one that is only three versions behind?

**Comment by Runemoro** [comment]
It should, especially since there is nothing in the forge changelog which should fix this.

**Comment by DWX12** [comment]
Thanks for the quick response. I usually only update forge if there's a mod that needs it or some other issue. Keep up the good work.

**Comment by Runemoro** [comment]
@DWX12 So updating forge worked?

**Comment by DWX12** [comment]
@Runemoro 

I didn't feel I needed to update forge since my issue was resolved by removing Thaumic Additions. I really don't know why I got that crash with VanillaFix or what the issue was with it. If, for whatever reason, I receive that specific error again, I'll see if updating forge fixes it first before I post here again.

Thank you for your time and for your great mod.

**Comment by Runemoro** [comment]
I'm not able to reproduce it. Is this still a problem with the latest forge, chisel, and thaumic additions?

**Comment by Hypsellis** [comment]
I get the same crash while I don't use Thaumic Additions.

**Comment by ZombieHDGaming** [comment]
@Hypsellis You're missing Zerocore
```
[20:04:17] [main/ERROR]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod bigreactors (Extreme Reactors) requires [zerocore@[1.12-0.1.2.2,)]
```
Add that and try again.

**Comment by ZombieHDGaming** [comment]
@DWX12 You're missing HammerCore and that's why the game is throwing a fit. See if adding that fixes it on your end. There's something we need to fix on our end, but that should hopefully fix it for you.

**Comment by Hypsellis** [comment]
Oh I had ZeroCore, but Twitch hadn't updated it well. I didn't know it could come from here since it's VanillaFix which crashed. Thanks for the help. ;)

**Comment by DWX12** [comment]
Again, not sure why I got that error in the first place, but ever since removing Thaumic Additions + Hammercore (which I had added when I had gotten that error, as far as I'm aware of), I haven't had any problems.

Thanks for all the help.

**Comment by Runemoro** [comment]
@DWX12 The problem was that VanillaFix made Forge's "Missing Dependency" screen crash. If you don't have a missing dependency, then the missing dependency screen doesn't show up.

**Comment by ZombieHDGaming** [comment]
@DWX12 you didn't have HammerCore installed according to your log, that's what caused the weird error :P

**Comment by Hypsellis** [comment]
In the case of Chisel it's probably because it misses Connected Textures.

**Comment by Runemoro** [comment]
@Hypsellis No, the issue only happens when Chisel is installed, no matter what the missing mod is. The VanillaFix support for Chisel is what was breaking the missing dependency screen.
