### ISSUE TITLE
1.8.9 support

### ISSUE THREAD

**Issue by Eddi2015** [DimensionalDevelopment/VanillaFix#5]
I'm not able to connect to any server. It doesn't crash, but it freezes at "logging in". Without your mod it works just fine. I can tell you all the mods if you need.
stacktrace here: https://privatebin.net/?9e53abe80aa5d9d4#I0T94ka8U8W2ITehHNcrH5pnq3NiBzc7eLIuW5+9mpk=

**Comment by Runemoro** [comment]
The teleportation fix seems to be incompatible with one of your mods. Does it still happen with only VanillaFix? If not, then could you either find which mod is incompatible, or upload a zip of all your mods (or a link to CurseForge if the modpack is on CurseForge)?

**Comment by Eddi2015** [comment]
Uploading all mods seems to be illegal (Optifine, LabyMod) but I will check and report

**Comment by Eddi2015** [comment]
Ok tested it! It's just VanillaFix alone. Something wrong with the fields/ injection?

**Comment by Runemoro** [comment]
What version of forge?

**Comment by Eddi2015** [comment]
latest forge for 1.8.9 something w/ 2318

**Comment by Eddi2015** [comment]
Issue happens with build 6 and 13

**Comment by Runemoro** [comment]
The mod isn't supported for versions older than 1.12 yet. Maybe in the future it will be, but it's not a priority for now.

**Comment by Eddi2015** [comment]
log w/ build 13: https://privatebin.net/?53d0c6e48421ee49#gxuIc6QefifjJrNQxZ8eFAY6eVqxvnzT+5t6Eq4sCZE=

**Comment by Eddi2015** [comment]
maybe (if you have time) you can have a look at the log. (attention: expires after 6 days)

**Comment by Runemoro** [comment]
This won't be done any time soon. A port to 1.7.10 may be done in the next few weeks, since that's a more popular version.
