### ISSUE TITLE
Graphics state needs to be reset after a crash

### ISSUE THREAD

**Issue by Xiaminou** [DimensionalDevelopment/VanillaFix#50]
Crash 1:
![2018-05-29_17 35 20](https://user-images.githubusercontent.com/8670392/40670475-ace17464-6369-11e8-87ae-e67a19e338fa.png)
Crash 2:
![2018-05-29_17 37 43](https://user-images.githubusercontent.com/8670392/40670474-acc3d0c6-6369-11e8-9287-26fde5be1a73.png)

Minecraft: 1.12.2
Forge: 2705
Mods: [list-alphabetical.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/2049094/list-alphabetical.txt)

**Comment by ZombieHDGaming** [comment]
I'm not sure if this is an issue caused by VanillaFix. We don't touch the main GUI or anything that would cause that. If you can reproduce this with just VanillaFix, then we might be able to fix it, but as of now, I'm not sure this is caused by us.

**Comment by Runemoro** [comment]
@ZombieHDGaming This is very likely caused by VanillaFix. Either the crash happened during some rendering code, or another mod is affecting the screen darkness and is using a static field which does not reset after post-init objects are cleared.

**Comment by Runemoro** [comment]
@Xiaminou Does it happen for all crashes? Try pressing F3 + C, does that make the screen darker too? If not, could you upload a crash report of the crash that caused the screen to get darker? If yes, do you know of any mods that may have a feature that makes the screen temporarily (VF could be making the temporary effect permanent)?
