### ISSUE TITLE
Question about the Increased block and item ID limits.

### ISSUE THREAD

**Issue by BeardStroker** [DimensionalDevelopment/VanillaFix#54]
My world was created using the NotEnoughId's mod, and I just want to make sure I don't mess something up horribly by updating VanillaFix while still using that mod. I tested it on a duplicate world, and it seems to work fine when just updating, but if I remove NotEnoughId's while using the update then minecraft crashes. So is it just a matter of feature overlap, or will it probably cause long term issues?

**Comment by Runemoro** [comment]
VanillaFix's ID limit feature does not modify the world format, but NEID does. Worlds created with NEID will still work properly with NEID installed, even after VanillaFix is installed.

**Comment by Runemoro** [comment]
Please make a backup of the world before, though, in case something unexpected does go wrong (and report it here if it does).

**Comment by BeardStroker** [comment]
Thanks for the quick reply, will report back if something comes up but hopefully it won't be necessary. Good luck with further development :)
