### ISSUE TITLE
Fix huge move packet client-side when colliding with ender dragon

### ISSUE THREAD

**Issue by Ghostrider231** [DimensionalDevelopment/VanillaFix#55]
Version: 1.0.7-70

To reference back to the original issue about the Ender Dragon, which doesn't actually hurt entities while landed in version **1.9 15w33a** said this specifically:

15w33a | Wings no longer deal damage while the Ender Dragon is landed.
-- | --

Which was from (history): https://minecraft.gamepedia.com/Ender_Dragon#History
Doesn't say or mention anything about readding Ender Dragon dealing damage while landed in later updates.

I wasn't referring to the Breath Attack. 

So the Ender Dragon dealing damage while landed in vanilla used to happen.

Hopefully I'm not confusing anyone.

----------------------------------------

**(In Creative Only)**
(Yes, to reference back to the original issue I've posted, which was partially fixed. The knock back effect is still there, but way less extreme. So It's not invalid!)

For whatever reason with this installed, when fighting the Ender Dragon (most notably while it's landed) you can't hurt it while it's landed unless you're really close to it. (More Closer then vanilla)

If I do the same procedure like trying the fight Ender Dragon without this mod. I can hurt the Ender Dragon at a more reasonable melee distance again.

I've assumed my melee attack reach was messed up but I've tested it on a normal mob, which lets me attack him at normal reach.

**(In Survival)**

This also included the wonky hitbox as well.

For some interesting reason, if a player is in survival mode while fighting the Ender Dragon. If they attempt to attack the Ender Dragon while it's landed. **It's possible that they can actually die Instantly instead. Regardless of their health.**

In Vanilla, only the initial of the landed phase will only hurt and fling you While accommodating the normal fall damage on the player.

**I can provide a video of the issue If necessary.**

**(With Only VanillaFix Installed):**
[Mods List]
![pic](https://user-images.githubusercontent.com/36087678/40866344-0d207330-65b2-11e8-880f-94e6fd368ebd.png)

[Video]
https://youtu.be/Hrn46seD_PA

Heck, I even got flunged/teleported

============================

**(Vanilla, using Forge Client):**
[Mods List]
Well, it's actually an empty folder. So no point of showing that.

[Video]
https://youtu.be/eoOeDNG4FpU

No teleporting and no wonky hitbox!

**Comment by Ghostrider231** [comment]
Yeah, I'll let you know and soon as the Ender Dragon stops taking it's sweet time that is.

**Comment by Ghostrider231** [comment]
Okay videos are there.

**Comment by grydian** [comment]
I also have this problem with the ender dragon.

**Comment by Runemoro** [comment]
Figured it out! This is caused by two things:
  - A vanilla bug causes the player to send a huge move packet (hundreds of blocks) when colliding with the Ender Dragon
  - VanillaFix disabled the movement speed anti-cheat check because it was breaking other mods. Vanilla's anti-cheat refuses the move and logs a "Player moved too quickly message", but VanillaFix accepts the move
