### ISSUE TITLE
Merge AttributeFix raised limits

### ISSUE THREAD

**Issue by TehSeph** [DimensionalDevelopment/VanillaFix#57]
After seeing [NotEnoughIDs](https://minecraft.curseforge.com/projects/notenoughids)' changes were added into this mod, it got me thinking that [AttributeFix](https://minecraft.curseforge.com/projects/attributefix)'s changes might also fit well into this mod.

**Comment by Runemoro** [comment]
This may become part of NotEnoughIDs instead.

**Comment by TehSeph** [comment]
Would you mind linking to JustEnoughIDs and is it compatible with VanillaFix?

**Comment by Runemoro** [comment]
It's not published yet. The ID limit code is being split from VanillaFix into JustEnoughIDs.

**Comment by TehSeph** [comment]
[JustEnoughIDs](https://minecraft.curseforge.com/projects/jeid) - Here is the link for anyone who might come across this in the future.
