### ISSUE TITLE
[1.0.7.72] Fast downward movement broken

### ISSUE THREAD

**Issue by chland** [DimensionalDevelopment/VanillaFix#58]
From the 1.0.7.72 changelog:

> Disabled anti-cheat temporarily, until the movement bugs are fixed

I guess this change was made to fix the random damage ticks? But it seems to have broken Elytras, falling from great heights, etc. (basically: everything where you move downwards fast). Just do a simple 

> /tp @p ~ 300 ~

and while fallig down you'll experience really bad stuttering as if the fall-speed is reset to 0. The same happens if you fly downwards using an elytra - its even worse and movement becomes were choppy.

**Comment by Runemoro** [comment]
Fixed for next release.
