### ISSUE TITLE
Extend biome ids

### ISSUE THREAD

**Issue by Hypsellis** [DimensionalDevelopment/VanillaFix#60]
I wonder if it was possible. I know this is something which has already been requested to Forge, and it seemed to be a huge pain to do. It would need to remake the way Minecraft manage the world datas.

**Comment by Hypsellis** [comment]
Here is all the discussion we had on Minecraft Forge github, if it can help you.
https://github.com/MinecraftForge/MinecraftForge/issues/1704

**Comment by Runemoro** [comment]
This will be part of NotEnoughIDs instead.
