### ISSUE TITLE
NoClassDefFoundError: Could not initialize org.dimdev.vanillafix.textures.ModCompatibility 

### ISSUE THREAD

**Issue by Hypsellis** [DimensionalDevelopment/VanillaFix#61]
I come back with this crash because it still happens to me. I use Forge 14.23.4.2707. Here is the crash report and log.
https://pastebin.com/LD9hJUzP
https://pastebin.com/utv8eE8W

**Comment by Runemoro** [comment]
Duplicate of #48

**Comment by Hypsellis** [comment]
I don't use Thaumic Additions

**Comment by Runemoro** [comment]
The issue happens with a few mods. The title includes Thaumic Additions because it's one of them, just to know how to reproduce the issue.
