### ISSUE TITLE
IDs >4096 wrapping around when saving world

### ISSUE THREAD

**Issue by Sunconure11** [DimensionalDevelopment/VanillaFix#62]
https://cdn.discordapp.com/attachments/362322551684464643/452679797328314379/Screenshot_2018-06-02_23.47.00.png

According to one person, stuff like this is indicative of an ID shift. This keeps popping up every time I create a world, and then enter it.

It seems to be placing fluids where it should not be, such as various milks from animania, wildberry juice from rustic, and so on.

**Comment by ProsperCraft** [comment]
I am having this with a fresh new world, I used Not Enough Ids prior(again new world, not an NEI worlds).

The blocks in the world look like they are in an old world, where the item ids shifted.

![2018-06-06_09 53 03](https://user-images.githubusercontent.com/4427684/41052962-9149df48-6977-11e8-8596-35852382f104.png)
![2018-06-06_09 53 08](https://user-images.githubusercontent.com/4427684/41052963-936c332a-6977-11e8-8385-24bc5d02cb87.png)

This is on my Ancient TownCraft modpack if you want to test, update all mods and remove bedbugs and Not Enough Ids.  
https://minecraft.curseforge.com/projects/ancient-towncraft

**Comment by Runemoro** [comment]
Yes, there's an issue with IDs >4096, keep using both NEID and VF for now.

**Comment by Hypsellis** [comment]
Sadly the bug still happens with some biomes.

**Comment by Runemoro** [comment]
@Hypsellis What do you mean? Are you using JEID? If yes, then report it in the JEID repo. If you mean worldgen, that's fixed in JEID.

**Comment by Hypsellis** [comment]
No I don't use it, but it works fine with JEID.
