### ISSUE TITLE
Server crash with "NOTIFICATION" setting

### ISSUE THREAD

**Issue by Jacky10X** [DimensionalDevelopment/VanillaFix#64]
Version: VanillaFix-1.0.8-82.jar
Problem : Cause the Server crash and shutdown
Real cause issue: Config default setting problem 
Below have detail information

**Comment by Janitor53** [comment]
Try to set S:scheduledTaskExceptionAction and S:scheduledTaskproblemAction in vanillafix.cfg to LOG

**Comment by Jacky10X** [comment]
It is really similar to https://github.com/DimensionalDevelopment/VanillaFix/issues/51
So i think it maybe better to change  default setting should be LOG 
or check if is it server side or client side 
if server side then setting should be LOG 
if client side then setting should be WARNING_SCREEN

**Comment by Jacky10X** [comment]
find the issue 
S:scheduledTaskproblemAction default setting is NOTIFICATION which cause the server crash

**Comment by Runemoro** [comment]
By the way, if you had NEID before, you'll need to keep it unless you want to restart with a new world.

**Comment by Runemoro** [comment]
The notification option is equivalent to log on the server and is working properly in 1.0.7. This may have just been an unrelated crash. If it keeps happening, make a new issue with a crash report.
