### ISSUE TITLE
Crash with chisel

### ISSUE THREAD

**Issue by tyler489** [DimensionalDevelopment/VanillaFix#69]
This was reported to eio on the enderio discord. Though i would inform you. Since it has nothing to do with enderio
https://pastebin.com/4EJuvvWs

https://pastebin.com/AqrwwQzS

**Comment by Runemoro** [comment]
Duplicate of #48. The problem is that VanillaFix breaks the "Missing Dependency" screen when chisel is installed. The real cause is that one of your mods is missing a dependency. Add it and it won't crash anymore.
