### ISSUE TITLE
Crash on startup with VanillaFix + Chisel & Bits + FoamFix + NEID not installed + >4096 block IDs

### ISSUE THREAD

**Issue by aking4125** [DimensionalDevelopment/VanillaFix#70]
When adding VanillaFix to my pack it crashes on start up indicating an issue with either FoamFix and or Chisel & bits. But when only those 3 are loaded, Minecraft loads and works perfectly fine. And if only VanillaFix is removed from the pack with all the mods, Minecraft loads and works perfectly fine. Any ideas? 

https://paste.dimdev.org/cadaselavu.mccrash

**Comment by Runemoro** [comment]
If you remove just FoamFix, does the issue still happen?

**Comment by aking4125** [comment]
After taking significantly longer. The pack does load without FoamFix. However, the Memory usage is out of control. The pack eats the full 8GB of RAM even before the 6/7 step and unless I feed it more RAM, it's suffering from terrible stuttering to the point that it's unplayable. So FoamFix is required for that.

But to answer it, yes removing FoamFix causes the pack to load (Albeit at the serve increase in memory).

**Comment by Runemoro** [comment]
Do you have more than 4096 block IDs (did you replace NEID with VanillaFix)?

**Comment by aking4125** [comment]
Most likely, I had NEID before VanillaFix was installed. I initially replaced NEID cause on the CurseForge page it reads it increases the ID limit just like NEID. Then I saw the bug on another post here about it shifting the IDs around. However, the pack doesn't load either way if NEID is there or not when VanillaFix is installed.

**Comment by Runemoro** [comment]
I did some testing. Chisel and Bits is incompatible with the way VanillaFix increases the ID limit (but not NEID since it breaks compatibility with vanilla).

For now keep using both NEID and VanillaFix if you have Chisel and Bits installed. Also, remember that even once this issue will be fixed, removing NEID will break all worlds created in NEID, so unless you want to start over, keep using NEID.

**Comment by Rongmario** [comment]
May I add, LittleTiles, which arguably mirrors Chisels&Bits' contents in a more minimal and efficient way and is a great alternative if you still are facing some troubles.

**Comment by Runemoro** [comment]
Fixed in latest dev build.

**Comment by Fireztonez** [comment]
Same issue my side, so thank's I will wait for the update :).

**Comment by Fireztonez** [comment]
I just try with the Last Dev Build (1.9.93), and it crash with McJtyLib and RFTools.

I know this is still in development, so you still work on the update, but I want to make sure you know there have problem with somes other mods now...

Crash Repport: https://paste.dimdev.org/ufaheluhic.mccrash

**Comment by ZombieHDGaming** [comment]
@Fireztonez We moved the ID limit feature to our new mod, JustEnoughIDs, and removed it from VanillaFix. We'll drop a link to the project once it's released.

**Comment by Fireztonez** [comment]
Ok,
Thank's for that information... I enjoy the fact of all mod called Not Enough and Just Enough...

I can not wait to finally remove Not Enough IDs and replace Just Enough ID's from my modpack!!
Fireztonez
