### ISSUE TITLE
Incompatibility With Sponge

### ISSUE THREAD

**Issue by AngelusQQ** [DimensionalDevelopment/VanillaFix#71]
https://pastebin.com/BDLURc2b

Update with the Latest Version of VanillaFix on CurseForge (VanillaFix-1.0.8-88) causes the server to not load within 10 seconds again. 

However the development build mentioned from [#53](https://github.com/DimensionalDevelopment/VanillaFix/issues/53)
works fine

**Comment by Runemoro** [comment]
Fixed in latest dev build.
