### ISSUE TITLE
Texture optimization code assumes quad.getSprite() is not null

### ISSUE THREAD

**Issue by vrork** [DimensionalDevelopment/VanillaFix#73]
If i search for cobalt in my modpack with vanilla fix enabled, it crashes, and close the minecraft instance. I am not sure wich item is causing the crash but disabling the vanilla fix fixed it

https://github.com/mezz/JustEnoughItems/issues/1257
https://paste.dimdev.org/ewewujaget.mccrash

Vanilla Fix: 1.0.8-88
Forge: 14.23.4.2707
MC: 1.12.2

**Comment by Runemoro** [comment]
Fixed in latest dev build.
