### ISSUE TITLE
Animation for avaritia singularities don't work

### ISSUE THREAD

**Issue by Hypsellis** [DimensionalDevelopment/VanillaFix#74]
Everything is in title.

**Comment by ShadowofCubes** [comment]
See also #40

**Comment by Hypsellis** [comment]
Oh sorry I hadn't seen it since it was closed. I suppose it has been fixed and I should close this issue.

**Comment by Robijnvogel** [comment]
I'm not quite certain that this issue was fixed, though.

**Comment by ShadowofCubes** [comment]
It isn't fixed

**Comment by Robijnvogel** [comment]
I have explained this particular issue to @Runemoro adding that animation of the white noise in the background of the Pile of Neutrons item etc. is broken by VanillaFix as well.

I wonder what animation shenanigans Morpheus might be doing that clash so badly with VF. :smile:

**Comment by Runemoro** [comment]
Fixed
