### ISSUE TITLE
Useless popup?

### ISSUE THREAD

**Issue by SilverKytten** [DimensionalDevelopment/VanillaFix#75]
v.1.0.8.88 running with 100+ other mods [modpack](https://www.technicpack.net/modpack/run-with-nature---test.925077/mods), multiplayer
This pops up, goes away, pops up, goes away, pops up, etc.

I don't know if it's ctrl+i or ctrl+L, but neither does anything. 

![image](https://user-images.githubusercontent.com/2188185/41272250-06903d22-6dda-11e8-9ef1-69c891ba3360.png)

**Comment by Runemoro** [comment]
Not useless, one of your other mods is causing an error and VanillaFix is telling you. If you don't like it, open the mod's config and disable it (set `scheduledTaskAction` to `LOG`).

**Comment by SilverKytten** [comment]
I cannot paste it's link because Ctrl+I does not do ***anything***, which I mentioned in the OP

**Comment by Runemoro** [comment]
Ctrl + I should open a window with a full report if you press it while the popup is open. Could another one of your mods be using the Ctrl + I keyboard combination?

Also, as I mentioned in my last comment, you can disable this in the mod's config if this happens too frequently.

**Comment by SilverKytten** [comment]
I would think that no other mod is using Ctrl+I combo on the main menu but I suppose it's possible. I'll try removing Vanillafix and see if something happens when I hit that.

**Comment by Runemoro** [comment]
Oh, `Ctrl+I` only works ingame for now. That's the problem. If it only happens on the main menu, you can join a world while the popup is still open and quickly press Ctrl+I. If that's not fast enough, you can also find the report in your `crash-reports` folder (even though it's not an actual crash).

**Comment by ZombieHDGaming** [comment]
If you're in the main menu, it won't work as you are no longer in-game. If you're in a world and it pops up, then it should work when pressing Ctrl + I and show the task exception screen
