### ISSUE TITLE
Crash when displaying crash screen

### ISSUE THREAD

**Issue by mezz** [DimensionalDevelopment/VanillaFix#78]
Somewhat related to https://github.com/DimensionalDevelopment/VanillaFix/issues/50
Resetting the render state can actually be a fairly big issue when an item crashes during rendering because the vanilla `BufferBuilder` is extremely fragile and can keep crashing with "Already building" if its state is not cleared.

Here's a log that was reported to me where VanillaFix itself crashes while trying to show a crash report because the `BufferBuilder` is in a bad state: 
(original crash at line 23553, VanillaFix crash at 24162)
https://paste.ee/p/ZNzfb

I used to catch and suppress these render errors in JEI, but unfortunately I have run into this and similar problems with other mod's rendering implementations (not just `BufferBuilder`). I didn't think it was worth trying to work around these issues any more because it was not reliable and I would be obscuring the original crash, so I just let the game crash normally on render errors now. You can get away with more hacking than I can in JEI so it is probably solvable.

**Comment by Runemoro** [comment]
Done. All `BufferBuilder`s are now reset after a crash. 
https://github.com/DimensionalDevelopment/VanillaFix/commit/35fc330095fee71be6322eec91063e493cbec01a#diff-2d5d3d58c30a1007a1065c5c80ddba0bR8

**Comment by mezz** [comment]
Looks good, thanks!
