### ISSUE TITLE
Fall damage prevention

### ISSUE THREAD

**Issue by Froggy800** [DimensionalDevelopment/VanillaFix#8]
The mod prevents the player from getting fall damage most of the times. Mobs are unaffected.
Tested on VanillaFix version 1.0.1-6 and Forge version 14.23.3.2655.

**Comment by ZombieHDGaming** [comment]
Can confirm that this does happen after going through a nether portal. Will speak with Rune and we'll see if we can get this fixed 😃

**Comment by Froggy800** [comment]
From my testing the issue doesn't appear to be related to dimension traveling; I simply created a new world and jumped off a cliff without getting hurt.

**Comment by Runemoro** [comment]
Yes, since the player is also invulnerable when joining the game until the client confirms the position.

**Comment by Runemoro** [comment]
You're right, this is related to fall distance not being calculated correctly rather than dimension change invulnerability.

**Comment by Runemoro** [comment]
Finally fixed this. I never thought I'd be so happy to see a "hit the ground too hard" message :)
