### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by DeadSix27** [DimensionalDevelopment/VanillaFix#80]
Crash log: https://0x0.st/sLGw.txt

Also, any idea why spongepowered is mentioned despite me not using spongeforge?

As seen in the log I use regular forge

**Comment by ZombieHDGaming** [comment]
That's because both VanillaFix and JEID both use a utility called Mixins to run both the mods. This an issue on JEID's end and will be fixed for the next release.

**Comment by DeadSix27** [comment]
I just realized I posted this on VanillaFix instead of JEID .. but you work on both anyway and thanks for the info :).

**Comment by Runemoro** [comment]
Fixed in latest JEID dev build.
