### ISSUE TITLE
Incompatibility with Replay mod

### ISSUE THREAD

**Issue by MNLegoBoy** [DimensionalDevelopment/VanillaFix#81]
I was testing out new mods, this was one of them, and my game kept crashing, I installed the latest version of forge, nothing changed, so added mods individually, VanillaFix being the first, when i put the Replay Mod in that is when it started to crash

**Comment by ZombieHDGaming** [comment]
Crash log please?

**Comment by MNLegoBoy** [comment]
[crash-2018-06-22_11.30.20-client.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/2128441/crash-2018-06-22_11.30.20-client.txt)

![mods](https://user-images.githubusercontent.com/29781187/41788095-2c9f6e5a-7610-11e8-8a34-da1a92df21e4.PNG)

I dont know why, but it works with just the replay mod and vanilla fix, but not with all my other mods with replay and vanilla fix, i think the game, or i am just being stupid

**Comment by ZombieHDGaming** [comment]
According to the log, the issue seems to be the 5zig mod, but it doesn't show up as a mod in the crash log which seems kind of weird. See if the issue persists with all your mods in besides the 5zig mod added.

**Comment by MNLegoBoy** [comment]
It works without 5zig, so there might be an incompatibility with 5zig

**Comment by ZombieHDGaming** [comment]
I figured as much. I'd suggest either making an issue on the ReplayMod issue tracker or where ever the 5zig mod is located and where the dev may read it.
