### ISSUE TITLE
[1.12.2] no chisel Futura block animation

### ISSUE THREAD

**Issue by TheSnowyChickens** [DimensionalDevelopment/VanillaFix#83]
Hello,

the futara block, from chisel, has no animation. (And I think all the other versions from this block too, like the "ME Controller")
![grafik](https://user-images.githubusercontent.com/29357962/41811666-3c4b9acc-7714-11e8-9423-935383e7c514.png)

VanillaFix-1.0.9-97.jar
1.12.2 - 14.23.4.2705
Chisel - MC1.12.2-0.2.0.31
CTM - MC1.12-0.3.0.15

**Comment by TheSnowyChickens** [comment]
Yes, opti is installed. (I dont have antialiasing activated, like in the other issue)

**Comment by Runemoro** [comment]
It seems like Chisel changed something in the latest version so the compatibility is no longer working.

**Comment by TheSnowyChickens** [comment]
The CTM mod changed alot with the last patch, they have to be the reason.

And the Fans (Factory Block) dont have no animations too.

**Comment by Runemoro** [comment]
Everything seems to be working properly for me with the latest version of Chisel (0.2.0.31)... What version of Chisel are you using?

**Comment by TheSnowyChickens** [comment]
Chisel-MC1.12.2-0.2.0.31
CTM-MC1.12-0.3.0.15
1.12.2 - 14.23.4.2705
VanillaFix-1.0.9-97

Maybe I forgot to say, that this MC project is on a Server and the Server doesn't have VF installed. :)

**Comment by MasterEnderman** [comment]
I have the same issue aswell but I'm not using Optifine. 

This can be fixed by setting the `textureFixes` to `false`.

**Comment by TheSnowyChickens** [comment]
Okay, I turn it off.
Thanks.
