### ISSUE TITLE
Breaks with AbyssalCraft

### ISSUE THREAD

**Issue by Sketaful** [DimensionalDevelopment/VanillaFix#87]
When using this together with [AbyssalCraft](https://minecraft.curseforge.com/projects/abyssalcraft) the client breaks on both SP and Server when placing one of the special fires it has. Don't know what or who is behind the problem, but atleast now you know.

The errorlog when placing it:
[https://paste.dimdev.org/ipinuliruc.mccrash](https://paste.dimdev.org/ipinuliruc.mccrash)

The errorlog when trying to relogg/start the map again after placing it:
[https://paste.dimdev.org/locemiwuwu.mccrash](https://paste.dimdev.org/locemiwuwu.mccrash)

**Comment by Robijnvogel** [comment]
Excuse me, but what exactly are you setting on fire? A Chisel wood block? If so, does this also happen when setting any Vanilla block on fire with this _Coralium_ Fire?

**Comment by Sketaful** [comment]
I set a regular grassblock on fire. I've actually hadn't even used chisel at the time.

**Comment by Robijnvogel** [comment]
It's [reproducible without Chisel installed](https://paste.dimdev.org/wigipagaqu.mccrash) and before the internal server crashes, the renderer seems to [go completely blank, only showing the fog colour of the biome you're in](https://i.imgur.com/wiECFGj.png).

**Comment by Sketaful** [comment]
Yes. I first thought placing the fire automatically teleported me to one of the others world or something :p

But the hole mod seemed a little uhm.. Messy.

**Comment by Robijnvogel** [comment]
@Shinoow do you have any idea what may be causing this?

**Comment by Shinoow** [comment]
Might be that my synthetic fire blocks override the wrong `getBoundingBox()` method when setting the null bounding box, which apparently changed a pretty long time ago (I don't have any workspaces with MC versions prior to 1.10.2 in them, but the fire block has already changed to overriding `getCollisionBoundingBox()` there). However, if this is the culprit of the crash, I find it very strange that it's taken at minimum 2 years before it has caused a crash. That's the theory I've come up with based on backtracking in the strack trace.

**Comment by Runemoro** [comment]
@Shinoow 
This only happens with VanillaFix because it calls the `shouldSideBeRendered` on blocks and sides with no quads (to determine visible quads), but vanilla checks that `!model.getQuads(state, side, rand).isEmpty()` before calling `shouldSideBeRendered`.

I changed the code to call `shouldSideBeRendered` only when vanilla also calls it in the latest version of VanillaFix.
