### ISSUE TITLE
Incompatibility with Custom Main Menu

### ISSUE THREAD

**Issue by Tollainmear** [DimensionalDevelopment/VanillaFix#90]
The problem is if the crash was handled by VanillaFix, this client would never connect to server again with a notice "Loging in...", and after a several minutes it would kick by server with reason "Connection Lost : Login time out", the only solution is close&restart the client.

![image](https://user-images.githubusercontent.com/25898067/42008389-d6d427fc-7ab7-11e8-8c38-c62d33f3e156.png)

#### It might be a display error, or it won't be kicked by server right?

I'm not sure weather this problem caused by vanillaFix, because if we disable the vanilla fix then let it crash normally, the situation is as the same with restart action 😅

**Comment by ZombieHDGaming** [comment]
I'm rather confused on what you're saying the issue is, can you give a better description of it? Also if the server is just plain Vanilla or modded please.

**Comment by Tollainmear** [comment]
I'm sorry about that, the detailed info is here:

Client:
- with forge 2655
- with vanilla fix 1.0.9-97

Test Server is:
- Using forge 2705
- without vanilla fix
- the issue happend on both SpongeVanilla and SpongeForge

And the step is:
- connect to a server using a modded client with vanilla fix
- press F3 + C to make it crash
- return to the multiplay page and connect to any server
- the issue occured

**Comment by ZombieHDGaming** [comment]
Can't seem to reproduce this issue on my end. While I didn't use a Sponge server as my test, I just used Hypixel for testing sake and I can't seem to reproduce it. Used F3 + C to "crash" the client, but clicked on the server and I joined just fine. Maybe try updating to the recommended Forge version on the client and see if that fixes it.

**Comment by Tollainmear** [comment]
I have test it again with only vanillaFix loaded(no more other mod) on forge 2655, and both connection of the hypixel and sponge server goes well, it seems like a incompatible issue, I'd do more test to find out the incompatible mod.

**Comment by Tollainmear** [comment]
@ZombieHDGaming Hi, can you replicate that issue?

**Comment by Slayer5934** [comment]
I've been waiting for this to be released since July, this mod hasnt had an "official" release since June 19th, any ETA?

**Comment by ZombieHDGaming** [comment]
I'll try and get it out at some point next week. Rune was working hard on Rift and the dev builds to get them working and him and I just started college up again, so we've been busy. I already have most of 1.0.10 picked and done, I'm just doing finalizing with some bugs and personal testing.

**Comment by Slayer5934** [comment]
Thank you for the update, I'm looking forward to the release :)
That college must be rough, but at least you have a field picked out to even start it, unlike me

**Comment by Slayer5934** [comment]
Ill be releasing my modpack update soon, just wanted to know an ETA if available for the VanillaFix update as I love the bug report feature and the crash catching that way users don't have to open the whole game again. Thank you for your time <3
