### ISSUE TITLE
Latest development version broken (NoClassDefFoundError BlockModelRenderer)

### ISSUE THREAD

**Issue by SteveKunG** [DimensionalDevelopment/VanillaFix#93]
I use VanillaFix latest development version (VanillaFix-1.0.10-104).
https://pastebin.com/eAcHM5bZ

**Comment by Runemoro** [comment]
We know about this problem, and it's not related to Optifine (happens with just VanillaFix when running outside of dev). We'll have to fix it before releasing to CurseForge. Until then you can use the CurseForge release.

**Comment by Runemoro** [comment]
Fixed
