### ISSUE TITLE
when i see the Botania spark Entity,the VanillaFix make my client Crash

### ISSUE THREAD

**Issue by MoeShimaKaze** [DimensionalDevelopment/VanillaFix#94]
Botania Version:r1.10-354
Forge Version:1.12.2-14.23.4.2705
VanillaFix Version:1.0.9-97
Mod list:https://pastebin.com/Zsf5A1wL
error logs:https://paste.dimdev.org/igiceqabuh.mccrash
when i join to the server and i watching the spark enity,the Cilent crash

**Comment by Runemoro** [comment]
Not related to VanillaFix
