### ISSUE TITLE
1.0.10-114 (Dynamic Model Loading, Caching Update) Bugs Thread

### ISSUE THREAD

**Issue by Rongmario** [DimensionalDevelopment/VanillaFix#99]
Log: https://gist.githubusercontent.com/Rongmario/afe7b3419a1d67d76c687b24a111a74d/raw/a8fa17b5c568d15046ef5f67bd288e43e31b46ff/gistfile1.txt

1. Buildcraft crash/incompatibility in the world: https://paste.dimdev.org/tatawobagi.mccrash
2. CodeChickenCore + Draconic Evolution (it depends on CCC) incompatibility: https://paste.dimdev.org/haqefufuye.mccrash
3. Agricraft incompatibility: https://paste.dimdev.org/zehaxekaqo.mccrash
4. OrbisAPI + Aether incompatibility: https://paste.dimdev.org/ugavasujuf.mccrash
5. My hand disappears sometimes?
6. Scrolling through JEI does this sometimes: 
![2018-07-20_22 41 18](https://user-images.githubusercontent.com/3684700/43012418-c33ae1ea-8c78-11e8-91cc-800e1f8c093d.png)
![2018-07-20_22 41 23](https://user-images.githubusercontent.com/3684700/43012419-c363f92c-8c78-11e8-86f0-8fd5f05ee017.png)
![2018-07-20_22 41 45](https://user-images.githubusercontent.com/3684700/43012421-c394eb86-8c78-11e8-8fd8-ce3c6cf44f3e.png)
7. Some sprites/models/textures displaying at all (after restarts/relog does not fix)
8. GregTech incompatibility: https://paste.dimdev.org/jopevosewu.mccrash
9. ProjectRed incompatibility: https://paste.dimdev.org/nulakugiwi.mccrash
10. Ztones block models don't load at all
11. Not yet compatible with launchers that aren't Vanilla (pathing, easily fixed)

More coming

**Comment by Runemoro** [comment]
@Rongmario These should be fixed in the latest dev build. Could you test to see if there are any other problems?

**Comment by Rongmario** [comment]
Will do. I'll get back to you.
